In [10]:

import numpy as np 
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

database ='database_final.sqlite'

In [11]:
con = sqlite3.connect(database)

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", con)
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...
8,table,Tags,Tags,305672,"CREATE TABLE Tags (ID int, player_api_id int, ..."
9,table,Twitter,Twitter,305673,CREATE TABLE `Twitter` (\n\t`Player_api_id`\tI...
10,table,Facebook,Facebook,305818,CREATE TABLE `Facebook` (\n\t`Team_api_id`\tIN...

A database like MySQL or PostgreSQL is considered a RDBMS (relational database management system) it's all in the name. You can through a normalised database structure of separate tables, join one or more tables together. 

In NoSQL the premise of joins is nonexistent, if you want to have relational data in a document database the general approach is to use embedded documents (sub-arrays within a key inside of a document) or reference objects of other documents.

We use joins in our relational database to convert and store the resulting dataset into a csv format

In [6]:
match = pd.read_sql("""SELECT * FROM Match""",con)
match

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
5,6,1,1,2008/2009,1,2008-09-24 00:00:00,492478,8203,8342,1,...,1.67,4.35,3.40,1.70,4.50,3.40,1.70,NaN,NaN,NaN
6,7,1,1,2008/2009,1,2008-08-16 00:00:00,492479,9999,8571,2,...,3.60,2.10,3.25,3.00,1.85,3.25,3.75,2.10,3.25,3.10
7,8,1,1,2008/2009,1,2008-08-16 00:00:00,492480,4049,9996,1,...,2.40,2.80,3.25,2.25,2.80,3.20,2.25,2.88,3.25,2.20
8,9,1,1,2008/2009,1,2008-08-16 00:00:00,492481,10001,9986,1,...,3.10,2.25,3.25,2.80,2.20,3.30,2.80,2.25,3.20,2.80
9,10,1,1,2008/2009,10,2008-11-01 00:00:00,492564,8342,8571,4,...,10.00,1.30,4.35,8.50,1.25,5.00,10.00,1.29,4.50,9.00
10,11,1,1,2008/2009,10,2008-10-31 00:00:00,492565,9985,9986,1,...,10.00,1.28,4.50,8.50,1.25,5.00,10.00,1.25,5.00,9.00
11,12,1,1,2008/2009,10,2008-11-02 00:00:00,492566,10000,9991,0,...,2.50,2.65,3.30,2.30,2.60,3.25,2.50,2.62,3.20,2.38
12,13,1,1,2008/2009,10,2008-11-01 00:00:00,492567,9994,9998,0,...,4.25,2.00,3.20,3.40,1.85,3.30,4.00,1.83,3.30,3.80
13,14,1,1,2008/2009,10,2008-11-01 00:00:00,492568,7947,10001,2,...,2.38,2.75,3.20,2.30,2.75,3.25,2.35,2.75,3.20,2.30
14,15,1,1,2008/2009,10,2008-11-01 00:00:00,492569,8203,9999,1,...,4.75,1.70,3.40,4.35,1.75,3.40,4.25,1.70,3.40,4.33
15,16,1,1,2008/2009,10,2008-11-01 00:00:00,492570,9996,9984,0,...,2.88,2.20,3.25,2.90,2.30,3.25,2.85,2.30,3.20,2.75
16,17,1,1,2008/2009,10,2008-11-01 00:00:00,492571,4049,9987,1,...,1.62,5.50,3.50,1.55,5.25,3.60,1.60,6.00,3.60,1.50
17,18,1,1,2008/2009,10,2008-11-02 00:00:00,492572,9993,8635,1,...,1.80,3.60,3.25,1.90,4.10,3.40,1.80,3.80,3.30,1.83
18,19,1,1,2008/2009,11,2008-11-08 00:00:00,492573,8635,9994,2,...,9.00,1.28,4.50,8.50,1.30,4.75,7.50,1.30,4.50,8.50
19,20,1,1,2008/2009,11,2008-11-08 00:00:00,492574,9998,9996,0,...,2.75,2.35,3.25,2.65,2.30,3.20,2.75,2.30,3.25,2.70
20,21,1,1,2008/2009,11,2008-11-09 00:00:00,492575,9986,8342,2,...,2.10,3.25,3.25,2.00,3.10,3.20,2.15,3.10,3.25,2.10
21,22,1,1,2008/2009,11,2008-11-07 00:00:00,492576,9984,10000,2,...,4.25,1.75,3.25,4.35,1.80,3.30,4.20,1.70,3.30,4.50
22,23,1,1,2008/2009,11,2008-11-08 00:00:00,492577,9991,7947,1,...,7.00,1.35,4.00,7.50,1.40,4.20,7.00,1.36,4.20,7.00
23,24,1,1,2008/2009,11,2008-11-08 00:00:00,492578,9999,4049,1,...,4.00,1.80,3.25,4.00,1.85,3.30,4.00,1.80,3.30,4.00
24,25,1,1,2008/2009,11,2008-11-08 00:00:00,492579,8571,8203,0,...,3.50,2.00,3.25,3.25,1.95,3.20,3.50,2.00,3.25,3.30
25,26,1,1,2008/2009,11,2008-11-08 00:00:00,492580,10001,9987,1,...,2.60,2.40,3.25,2.60,2.50,3.25,2.50,2.50,3.20,2.50
26,27,1,1,2008/2009,11,2008-11-09 00:00:00,492581,9993,9985,1,...,1.95,3.75,3.25,1.85,3.60,3.25,1.95,3.50,3.30,1.91
27,28,1,1,2008/2009,12,2008-11-16 00:00:00,492582,8342,8635,1,...,3.30,2.25,3.10,2.80,2.10,3.20,3.20,2.20,3.20,2.90
28,29,1,1,2008/2009,12,2008-11-15 00:00:00,492583,9987,9999,1,...,10.00,1.25,5.00,9.00,1.27,5.00,8.50,1.25,5.00,9.00
29,30,1,1,2008/2009,12,2008-11-15 00:00:00,492584,10000,9993,2,...,3.40,2.10,3.30,3.10,2.00,3.20,3.50,2.00,3.25,3.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25949,25950,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992066,9956,7896,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25950,25951,24558,24558,2015/2016,4,2015-08-08 00:00:00,1992067,10199,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25951,25952,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992068,10190,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25952,25953,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992069,9824,10179,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25953,25954,24558,24558,2015/2016,4,2015-08-09 00:00:00,1992070,10192,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25954,25955,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992071,9931,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25955,25956,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992072,10192,7896,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25956,25957,24558,24558,2015/2016,5,2015-08-12 00:00:00,1992073,10199,10190,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25957,25958,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992074,10179,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25958,25959,24558,24558,2015/2016,5,2015-08-13 00:00:00,1992075,9824,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25959,25960,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992076,7896,9931,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25960,25961,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992077,10179,10192,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,25962,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992078,10190,9956,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25962,25963,24558,24558,2015/2016,6,2015-08-23 00:00:00,1992079,10191,9824,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25963,25964,24558,24558,2015/2016,6,2015-08-22 00:00:00,1992080,10243,10199,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25964,25965,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992081,7896,10199,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25965,25966,24558,24558,2015/2016,7,2015-08-29 00:00:00,1992082,9824,10190,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25966,25967,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992083,10191,10179,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25967,25968,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992084,9931,10243,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25968,25969,24558,24558,2015/2016,7,2015-08-30 00:00:00,1992085,9956,10192,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,25970,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992086,9931,10190,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,25971,24558,24558,2015/2016,8,2015-09-12 00:00:00,1992087,10192,9824,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25971,25972,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992088,10199,9956,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,25973,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992089,10243,10191,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25973,25974,24558,24558,2015/2016,8,2015-09-13 00:00:00,1992090,10179,7896,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
matches_all = pd.read_sql("""SELECT Match.id, Country.name AS country_name,League.name AS league_name, season, stage, date,
            HT.team_long_name AS  home_team, AT.team_long_name AS away_team, home_team_goal, away_team_goal,
            
            H1.player_name AS home_player_1,H2.player_name AS home_player_2,H3.player_name AS home_player_3,
            H4.player_name AS home_player_4,H5.player_name AS home_player_5,H6.player_name AS home_player_6,
            H7.player_name AS home_player_7,H8.player_name AS home_player_8,H9.player_name AS home_player_9,
            H10.player_name AS home_player_10,H11.player_name AS home_player_11,
            
            A1.player_name AS away_player_1,A2.player_name AS away_player_2,A3.player_name AS away_player_3,
            A4.player_name AS away_player_4,A5.player_name AS away_player_5,A6.player_name AS away_player_6,
            A7.player_name AS away_player_7,A8.player_name AS away_player_8,A9.player_name AS away_player_9,
            A10.player_name AS away_player_10,A11.player_name AS away_player_11
                                
                                
                                FROM Match
                                JOIN Country on Country.id = Match.country_id
                                JOIN League on League.id = Match.league_id
                                LEFT JOIN Team AS HT on HT.team_api_id = Match.home_team_api_id
                                LEFT JOIN Team AS AT on AT.team_api_id = Match.away_team_api_id
                                
                                INNER JOIN Player AS H1 ON Match.home_player_1 = H1.player_api_id
                                INNER JOIN Player AS H2 ON Match.home_player_2 = H2.player_api_id
                                INNER JOIN Player AS H3 ON Match.home_player_3 = H3.player_api_id
                                INNER JOIN Player AS H4 ON Match.home_player_4 = H4.player_api_id
                                INNER JOIN Player AS H5 ON Match.home_player_5 = H5.player_api_id
                                INNER JOIN Player AS H6 ON Match.home_player_6 = H6.player_api_id
                                INNER JOIN Player AS H7 ON Match.home_player_7 = H7.player_api_id
                                INNER JOIN Player AS H8 ON Match.home_player_8 = H8.player_api_id
                                INNER JOIN Player AS H9 ON Match.home_player_9 = H9.player_api_id
                                INNER JOIN Player AS H10 ON Match.home_player_10 = H10.player_api_id
                                INNER JOIN Player AS H11 ON Match.home_player_11 = H11.player_api_id
                                
                                INNER JOIN Player AS A1 ON Match.away_player_1 = A1.player_api_id
                                INNER JOIN Player AS A2 ON Match.away_player_2 = A2.player_api_id
                                INNER JOIN Player AS A3 ON Match.away_player_3 = A3.player_api_id
                                INNER JOIN Player AS A4 ON Match.away_player_4 = A4.player_api_id
                                INNER JOIN Player AS A5 ON Match.away_player_5 = A5.player_api_id
                                INNER JOIN Player AS A6 ON Match.away_player_6 = A6.player_api_id
                                INNER JOIN Player AS A7 ON Match.away_player_7 = A7.player_api_id
                                INNER JOIN Player AS A8 ON Match.away_player_8 = A8.player_api_id
                                INNER JOIN Player AS A9 ON Match.away_player_9 = A9.player_api_id
                                INNER JOIN Player AS A10 ON Match.away_player_10 = A10.player_api_id
                                INNER JOIN Player AS A11 ON Match.away_player_11 = A11.player_api_id
                                                    
                                ORDER by date""",con)

matches_all

,id,country_name,league_name,season,stage,date,home_team,away_team,home_team_goal,away_team_goal,...,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11
0,4770,France,France Ligue 1,2008/2009,1,2008-08-09 00:00:00,Girondins de Bordeaux,SM Caen,2,1,...,Nicolas Seube,Florian Boucansaud,Jeremy Sorbon,Anthony Deroin,Benjamin Nivet,Gregory Proment,Reynald Lemaitre,Juan Eduardo Eluchans,Steve Savidan,Youssef Adnane
1,4771,France,France Ligue 1,2008/2009,1,2008-08-09 00:00:00,Le Havre AC,OGC Nice,1,0,...,Vincent Hognon,Cedric Kante,Olivier Echouafni,David Hellebuyck,Emerse Fae,Drissa Diakite,Cyril Jeunechamp,Loic Remy,Mahamane Traore,Habib Bamogo
2,4774,France,France Ligue 1,2008/2009,1,2008-08-09 00:00:00,AS Monaco,Paris Saint-Germain,1,0,...,Marcos Ceara,Mamadou Sakho,Zoumana Camara,Sylvain Armand,Claude Makelele,Jeremy Clement,Jerome Rothen,Ludovic Giuly,Guillaume Hoarau,Fabrice Pancrate
3,4775,France,France Ligue 1,2008/2009,1,2008-08-09 00:00:00,AS Nancy-Lorraine,LOSC Lille,0,0,...,Franck Beria,Gregory Tafforeau,Adil Rami,Mathieu Debuchy,Florent Balmont,Yohan Cabaye,Michel Bastos,Rio Mavuba,Pierre-Alain Frau,Nicolas Fauvergue
4,4777,France,France Ligue 1,2008/2009,1,2008-08-09 00:00:00,FC Sochaux-Montbéliard,Grenoble Foot 38,1,2,...,Maxence Flachez,Martial Robin,Milivoje Vitakic,Jimmy Mainfroi,Jacques Alaixys Romao,Sofiane Feghouli,Laurent Batlles,Milos Dimitrijevic,Daniel Moreira,Bouchaib El Moubarki
5,4778,France,France Ligue 1,2008/2009,1,2008-08-09 00:00:00,Valenciennes FC,AS Saint-Étienne,1,0,...,Efstathios Tavlaridis,Mouhamadou Dabo,Sylvain Monsoreau,Geoffrey Dernis,Blaise Matuidi,Christophe Landrin,Loic Perrin,Dimitri Payet,David Gigliotti,Pascal Feindouno
6,19695,Scotland,Scotland Premier League,2008/2009,1,2008-08-09 00:00:00,Heart of Midlothian,Motherwell,3,2,...,Paul Quinn,Stephen Craigan,Mark Reynolds,Steven Hammell,Steven McGarry,Stephen Hughes,Robert Malcolm,Keith Lasley,Chris Porter,David Clarkson
7,19696,Scotland,Scotland Premier League,2008/2009,1,2008-08-09 00:00:00,Kilmarnock,Hibernian,1,0,...,David van Zanten,Paul Hanlon,Robert Jones,Chris Hogg,Alan O'Brien,Joe Keenan,Steven Thicot,Dean Shiels,Steven Fletcher,Colin Nish
8,4773,France,France Ligue 1,2008/2009,1,2008-08-10 00:00:00,Olympique Lyonnais,Toulouse FC,3,0,...,Mohamed Fofana,Mauro Cetto,Jeremy Mathieu,Albin Ebondo,Etienne Didot,Pantxi Sirieix,Alexandre Bonnet,Daniel Omoya Braaten,Etienne Capoue,Andre-Pierre Gignac
9,19698,Scotland,Scotland Premier League,2008/2009,1,2008-08-10 00:00:00,Celtic,St. Mirren,1,0,...,Jack Ross,William Haining,John Potter,"Franco Miranda,22",Hugh Murray,Garry Brady,Stephen O'Donnell,Stephen McGinn,Billy Mehmet,Tom Brighton
10,7809,Germany,Germany 1. Bundesliga,2008/2009,1,2008-08-15 00:00:00,FC Bayern Munich,Hamburger SV,2,2,...,Jerome Boateng,Bastian Reinhardt,Joris Mathijsen,Collin Benjamin,David Jarolim,Nigel de Jong,Piotr Trochowski,Jonathan Pitroipa,Jose Paolo Guerrero,Ivica Olic
11,1730,England,England Premier League,2008/2009,1,2008-08-16 00:00:00,Arsenal,West Bromwich Albion,1,0,...,Carl Hoefkens,Leon Barnett,Abdoulaye Meite,Paul Robinson,Jonathan Greening,Do-Heon Kim,Chris Brunt,James Morrison,Marek Cech,Ishmael Miller
12,1731,England,England Premier League,2008/2009,1,2008-08-16 00:00:00,Sunderland,Liverpool,0,1,...,Alvaro Arbeloa,Jamie Carragher,Sami Hyypiae,Andrea Dossena,Dirk Kuyt,Steven Gerrard,Damien Plessis,Yossi Benayoun,Robbie Keane,Fernando Torres
13,1732,England,England Premier League,2008/2009,1,2008-08-16 00:00:00,West Ham United,Wigan Athletic,2,1,...,Mario Melchiot,Emmerson Boyce,Maynor Figueroa,Paul Scharner,Antonio Valencia,Lee Cattermole,Wilson Palacios,Olivier Kapo,Amr Zaki,Emile Heskey
14,1734,England,England Premier League,2008/2009,1,2008-08-16 00:00:00,Everton,Blackburn Rovers,2,3,...,Andre Ooijer,Christopher Samba,Ryan Nelsen,Stephen Warnock,David Dunn,Aaron Mokoena,Morten Gamst Pedersen,Steven Reid,Jason Roberts,Roque Santa Cruz
15,1735,England,England Premier League,2008/2009,1,2008-08-16 00:00:00,Middlesbrough,Tottenham Hotspur,2,1,...,Didier Zokora,Jonathan Woodgate,Michael Dawson,Benoit Assou-Ekotto,Aaron Lennon,Jermaine Jenas,Luka Modric,David Bentley,Giovani dos Santos,Darren Bent
16,1736,England,England Premier League,2008/2009,1,2008-08-16 00:00:00,Bolton Wanderers,Stoke City,3,1,...,Andy Wilkinson,Leon Cort,Ryan Shawcross,Andy Griffin,Rory Delap,Seyi Olofinjana,Glenn Whelan,Richard Cresswell,Dave Kitson,Mamady Sidibe
17,1737,England,England Premier League,2008/2009,1,2008-08-16 00:00:00,Hull City,Fulham,2,1,...,John Pantsil,Brede Hangeland,Aaron Hughes,Paul Konchesky,Simon Davies,Danny Murphy,Jimmy Bullard,Zoltan Gera,Ki-Hyeon Seol,Bobby Zamora
18,4884,France,France Ligue 1,2008/2009,2,2008-08-16 00:00:00,FC Nantes,AS Monaco,1,1,...,Francois Modesto,Vincent Muratori,Cedric Mongongu,Diego Perez,Nene,Jean-Jacques Gosso,Camel Meriem,Jerko Leko,Juan Pablo Pino,Frederic Nimani
19,4885,France,France Ligue 1,2008/2009,2,2008-08-16 00:00:00,OGC Nice,AS Nancy-Lorraine,2,1,...,Andre Luiz,Michael Basser Chretien,Abdeslam Ouaddou,Chris Malonga,Pascal Berenguer,Youssouf Hadji,Jonathan Brison,Benjamin Gavanon,Landry N'Guemo,Marc-Antoine Fortune
20,4886,France,France Ligue 1,2008/2009,2,2008-08-16 00:00:00,Paris Saint-Germain,Girondins de Bordeaux,1,0,...,Carlos Henrique,Franck Jurietti,Souleymane Diawara,Matthieu Chalme,Alou Diarra,Fernando,Yoann Gourcuff,Wendel,Yoan Gouffran,Fernando Cavenaghi
21,4887,France,France Ligue 1,2008/2009,2,2008-08-16 00:00:00,AS Saint-Étienne,FC Sochaux-Montbéliard,2,1,...,Carlao,Damien Perquis,Jacques Faty,Stephane Pichot,Stephane Dalmat,Romain Pitau,Mickael Isabey,Mevlut Erdinc,Alvaro Santos,Nicolas Maurice-Belay
22,7810,Germany,Germany 1. Bundesliga,2008/2009,1,2008-08-16 00:00:00,Bayer 04 Leverkusen,Borussia Dortmund,2,3,...,Antonio Rukavina,Neven Subotic,Mats Hummels,Dede,Jakub Blaszczykowski,Tamas Hajnal,Sebastian Kehl,Florian Kringe,Nelson Haedo Valdez,Diego Klimowicz
23,7812,Germany,Germany 1. Bundesliga,2008/2009,1,2008-08-16 00:00:00,VfL Wolfsburg,1. FC Köln,2,1,...,Umit Ozat,Geromel,Youssef Wasef Mohamad,Pierre Wome,Petit,Miso Brecko,Thomas Broich,Roda Antar,Milivoje Novakovic,Sergiu Marian Radu
24,7814,Germany,Germany 1. Bundesliga,2008/2009,1,2008-08-16 00:00:00,DSC Arminia Bielefeld,SV Werder Bremen,2,2,...,Clemens Fritz,Sebastian Proedl,Naldo,Sebastian Boenisch,Frank Baumann,Torsten Frings,Daniel Jensen,Aaron Hunt,Markus Rosenberg,Hugo Almeida
25,19760,Scotland,Scotland Premier League,2008/2009,2,2008-08-16 00:00:00,Rangers,Heart of Midlothian,2,0,...,Jason Thomson,Marius Zaliukas,Christophe Berra,Lee Wallace,Laryea Kingston,Michael Stewart,Christos Karypidis,Andrew Driver,Jamie Mole,Audrius Ksanavicius
26,19762,Scotland,Scotland Premier League,2008/2009,2,2008-08-16 00:00:00,Motherwell,Aberdeen,0,1,...,Zander Diamond,Scott Severin,Andrew Considine,Charles Mulgrew,Gary McDonald,Mark Kerr,Derek Young,Richard Foster,Lee Miller,Darren Mackie
27,1729,England,England Premier League,2008/2009,1,2008-08-17 00:00:00,Manchester United,Newcastle United,1,1,...,Habib Beye,Steven Taylor,Fabricio Coloccini,Charles N'Zogbia,James Milner,Danny Guthrie,Nicky Butt,Jonas Gutierrez,Damien Duff,Obafemi Martins
28,1738,England,England Premier League,2008/2009,1,2008-08-17 00:00:00,Chelsea,Portsmouth,4,0,...,Glen Johnson,Sol Campbell,Sylvain Distin,Hermann Hreidarsson,Papa Bouba Diop,Lassana Diarra,Younes Kaboul,Niko Kranjcar,Jermain Defoe,Peter Crouch
29,4880,France,France Ligue 1,2008/2009,2,2008-08-17 00:00:00,Grenoble Foot 38,Stade Rennais FC,1,0,...,Carlos Bocanegra,Rod Fanni,Petter Hansson,Lucien Aubey,Kader Mangane,Jerome Leroy,Fabien Lemoine,Mickael Pagis,Olivier Thomert,Jires Kembo-Ekoko
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21344,13204,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Genoa,Atalanta,1,2,...,Andrea Conti,Andrea Masiello,Berat Djimsiti,Davide Brivio,Marten De Roon,Roberto Gagliardini,Marco D'Alessandro,Remo Freuler,Alejandro Daro Gomez,Marco Borriello
21345,13205,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Chievo Verona,Bologna,0,0,...,Emil Krafth,Alex Ferrari,Luca Rossettini,Adam Masina,Matteo Brighi,Lorenzo Crisetig,Anthony Mounier,Franco Brienza,Emanuele Giaccherini,Sergio Floccari
21346,13206,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Udinese,Carpi,1,2,...,Cristian Zaccardo,Emanuele Suagher,Riccardo Gagliolo,Stefano Sabelli,Lorenzo Pasciuti,Marco Crimi,Raffaele Bianco,Rafael Martinho,Simone Verdi,Kevin Lasagna
21347,13207,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Lazio,Fiorentina,2,4,...,Nenad Tomovic,Gonzalo Rodriguez,Davide Astori,Federico Bernardeschi,Matias Vecino,Milan Badelj,Marcos Alonso,Matias Fernandez,Cristian Tello Herrera,Mauro Zarate
21348,13209,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Palermo,Hellas Verona,3,2,...,Eros Pisano,Matteo Bianchetti,Filip Helander,Urby Emanuelson,Federico Viviani,Luca Marrone,Pawel Wszolek,Artur Ionita,Giampaolo Pazzini,Luca Siligardi
21349,13213,Italy,Italy Serie A,2015/2016,38,2016-05-15 00:00:00,Empoli,Torino,2,1,...,Kamil Glik,Pontus Jansson,Emiliano Moretti,Davide Zappacosta,Daniele Baselli,Alessandro Gazzi,Joel Chukwuma Obi,Bruno Peres,Andrea Belotti,Josef Martinez
21350,19638,Portugal,Portugal Liga ZON Sagres,2015/2016,34,2016-05-15 00:00:00,SL Benfica,CD Nacional,4,1,...,Nuno Campos,Rui Correia,Alan Henrique,Mauro Cerqueira,Luis Aurelio,Boubacar Fofana,Washington,Joao Aurelio,Tiquinho,Salvador Agra
21351,19639,Portugal,Portugal Liga ZON Sagres,2015/2016,34,2016-05-15 00:00:00,SC Braga,Sporting CP,0,4,...,Matias Ezequiel Schelotto,Ruben Semedo,Sebastian Coates,Bruno Cesar,Gelson,Joao Mario,William Carvalho,Bryan Ruiz,Teofilo Gutierrez,Islam Slimani
21352,21479,Scotland,Scotland Premier League,2015/2016,38,2016-05-15 00:00:00,Aberdeen,Ross County FC,0,4,...,Chris Robertson,Paul Quinn,Scott Boyd,Raffaele De Vita,Alex Schalk,Liam Boyce,Jackson Irvine,Michael Gardyne,Brian Graham,Martin Woods
21353,21480,Scotland,Scotland Premier League,2015/2016,38,2016-05-15 00:00:00,Celtic,Motherwell,7,0,...,Marvin Johnson,Stephen McManus,Ben Hall,Luke Watt,Morgaro Gomis,Christopher Cadden,Lionel Ainsworth,Stephen Pearson,Scott McDonald,Louis Moult
21354,24491,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,Real Betis Balompié,Getafe CF,2,1,...,Santiago Vergini,Cala,Damian Suarez,Alvaro Pereira,Alvaro Medran,Juan Rodriguez,Pedro Leon,Pablo Sarabia,Moi Gomez,Stefan Scepovic
21355,24492,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,RCD Espanyol,SD Eibar,4,2,...,Borja Ekiza,Mauro Dos Santos,Ion Ansotegi,David Junca,Keko,Dani Garcia,Adrian Gonzalez,Antonio Luna,Sergi Enrich,Borja Baston
21356,24495,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,Málaga CF,UD Las Palmas,4,1,...,David Garcia,Pedro Bigas,Paolo Lemos,Dani Castellano,Roque Mesa,Nabil El Zhar,Tana,Jonathan Viera,Momo,Willian Jose
21357,24497,Spain,Spain LIGA BBVA,2015/2016,38,2016-05-15 00:00:00,Rayo Vallecano,Levante UD,3,1,...,Ivan Lopez,David Navarro,Carl Medjani,Juanfran Garcia,Simao,Verza,Jordi Feliu Xumetra,Ruben Garcia,Jefferson Lerma,Victor Casadesus
21358,25935,Switzerland,Switzerland Super League,2015/2016,34,2016-05-16 00:00:00,Grasshopper Club Zürich,FC Vaduz,1,2,...,Levent Guelen,Mario Buehler,Simone Grippo,Axel Borgmann,Philipp Muntwiler,Stjepan Kukuruzovic,Diego Ciccone,Dejan Janjatovic,Moreno Costanzo,Armando Sadiku
21359,25936,Switzerland,Switzerland Super League,2015/2016,34,2016-05-16 00:00:00,Lugano,BSC Young Boys,1,3,...,Florent Hadergjonaj,Milan Vilotic,Steve von Bergen,Jan Lecjaks,Sekou Junior Sanogo,Leonardo Bertone,Denis Zakaria,Miralem Sulejmani,Philipp Zulechner,Guillaume Hoarau
21360,25937,Switzerland,Switzerland Super League,2015/2016,34,2016-05-16 00:00:00,FC Luzern,FC Basel,4,0,...,Naser Aliji,Marek Suchy,Eray Cumart,Adama Traore,Alexander Fransson,Charles Pickel,Davide Calla,Birkir Bjarnason,Renato Steffen,Breel Embolo
21361,25938,Switzerland,Switzerland Super League,2015/2016,34,2016-05-16 00:00:00,FC St. Gallen,FC Zürich,3,0,...,Ivan Kecojevic,Cedric Brunner,Leonardo Sanchez,Philippe Koch,Sangone Sarr,Gilles Yapi,Moussa Kone,Davide Chiumiento,Kevin Bua,Alexandr Kerzhakov
21362,25939,Switzerland,Switzerland Super League,2015/2016,34,2016-05-16 00:00:00,FC Thun,FC Sion,1,1,...,Elsad Zverotic,Leo Lacroix,Reto Ziegler,Kay Voser,Veroljub Salatic,Vincent Sierro,Carlitos,Geoffrey Mujangi Bia,Martin Zeman,Theofanis Gekas
21363,4702,England,England Premier League,2015/2016,38,2016-05-17 00:00:00,Manchester United,Bournemouth,3,1,...,Simon Francis,Tommy Elphick,Steve Cook,Charlie Daniels,Matt Ritchie,Andrew Surman,Dan Gosling,Marc Pugh,Callum Wilson,Joshua King
21364,25940,Switzerland,Switzerland Super League,2015/2016,35,2016-05-22 00:00:00,Grasshopper Club Zürich,FC Thun,0,0,...,Kevin Bigler,Fulvio Sulmoni,Marco Buerki,Stefan Glarner,Gonzalo Zarate,Dennis Hediger,Michael Siegfried,Nelson Ferreira,Simone Rapp,Ridge Munsy
21365,25941,Switzerland,Switzerland Super League,2015/2016,35,2016-05-22 00:00:00,FC Sion,FC Zürich,2,2,...,Alain Nef,Ivan Kecojevic,Burim Kukeli,Philippe Koch,Gilles Yapi,Sangone Sarr,Vinicius,Oliver Buff,Alexandr Kerzhakov,Franck Etoundi
21366,25942,Switzerland,Switzerland Super League,2015/2016,35,2016-05-22 00:00:00,FC Vaduz,Lugano,0,0,...,Frederic Veseli,Matias Malvino,Orlando Urbano,Goran Jozinovic,Mario Piccinocchi,Jonathan Sabbatini,Domen Crnigoj,Ezgjan Alioski,Anastasios Donis,Mattia Bottani
21367,25943,Switzerland,Switzerland Super League,2015/2016,35,2016-05-22 00:00:00,BSC Young Boys,FC Basel,2,3,...,Naser Aliji,Marek Suchy,Eray Cumart,Adama Traore,Alexander Fransson,Luca Zuffi,Jean-Paul Boetius,Matias Emilio Delgado,Renato Steffen,Cedric Itten
21368,25944,Switzerland,Switzerland Super League,2015/2016,35,2016-05-22 00:00:00,FC St. Gallen,FC Luzern,1,4,...,Christian Schneuwly,Francois Affolter,Tomislav Puljic,Jerome Thiesson,Jakob Jantscher,Hekuran Kryeziu,Nicolas Haas,Jahmir Hyka,Michael Frey,Marco Schneuwly
21369,25945,Switzerland,Switzerland Super League,2015/2016,36,2016-05-25 00:00:00,FC Basel,Grasshopper Club Zürich,0,1,...,Moritz Bauer,Alban Pnishi,Jan Bamert,Benjamin Luethi,Marko Basic,Kim Kaellstroem,Nikola Gjorgjev,Mergim Brahimi,Caio,Munas Dabbur
21370,25946,Switzerland,Switzerland Super League,2015/2016,36,2016-05-25 00:00:00,Lugano,FC St. Gallen,3,0,...,Silvan Hefti,Roy Gelmi,Martin Angha,Florent Hanin,Mario Mutsch,Marco Aratore,Danijel Aleksic,Gianluca Gaudino,Steven Lang,Albert Bunjaku
21371,25947,Switzerland,Switzerland Super League,2015/2016,36,2016-05-25 00:00:00,FC Luzern,FC Sion,2,2,...,Elsad Zverotic,Birama Ndoye,Reto Ziegler,Vincent Ruefli,Martin Zeman,Veroljub Salatic,Vincent Sierro,Carlitos,Leo Itaperuna,Theofanis Gekas
21372,25948,Switzerland,Switzerland Super League,2015/2016,36,2016-05-25 00:00:00,FC Thun,BSC Young Boys,0,3,...,Scott Lee Sutter,Milan Vilotic,Steve von Bergen,Linus Obexer,Raphael Nuzzolo,Sekou Junior Sanogo,Leonardo Bertone,Miralem Sulejmani,Alexander Gerndt,Guillaume Hoarau
21373,25949,Switzerland,Switzerland Super League,2015/2016,36,2016-05-25 00:00:00,FC Zürich,FC Vaduz,3,1,...,Levent Guelen,Mario Buehler,Simone Grippo,Nicolas Hasler,Stjepan Kukuruzovic,Diego Ciccone,Axel Borgmann,Moreno Costanzo,Robin Kamber,Albion Avdijaj

In [4]:
matches_all.to_csv('non_rel_match.csv')

We are converting the dataframes to csv file to later import it into mongoDB

In [7]:
pd.read_sql("select * from player;",con)

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154
5,6,27316,Aaron Hunt,158138,1986-09-04 00:00:00,182.88,161
6,7,564793,Aaron Kuhl,221280,1996-01-30 00:00:00,172.72,146
7,8,30895,Aaron Lennon,152747,1987-04-16 00:00:00,165.10,139
8,9,528212,Aaron Lennox,206592,1993-02-19 00:00:00,190.50,181
9,10,101042,Aaron Meijers,188621,1987-10-28 00:00:00,175.26,170
10,11,23889,Aaron Mokoena,47189,1980-11-25 00:00:00,182.88,181
11,12,231592,Aaron Mooy,194958,1990-09-15 00:00:00,175.26,150
12,13,163222,Aaron Muirhead,213568,1990-08-30 00:00:00,187.96,168
13,14,40719,Aaron Niguez,183853,1989-04-26 00:00:00,170.18,143
14,15,75489,Aaron Ramsey,186561,1990-12-26 00:00:00,177.80,154
15,16,597948,Aaron Splaine,226014,1996-10-13 00:00:00,172.72,163
16,17,161644,Aaron Taylor-Sinclair,213569,1991-04-08 00:00:00,182.88,176
17,18,23499,Aaron Wilbraham,2335,1979-10-21 00:00:00,190.50,159
18,19,120919,Aatif Chahechouhe,187939,1986-07-02 00:00:00,175.26,150
19,20,46447,Abasse Ba,156626,1976-07-12 00:00:00,187.96,185
20,21,167027,Abdelaziz Barrada,192274,1989-06-19 00:00:00,177.80,161
21,22,245653,Abdelfettah Boukhriss,202425,1986-10-22 00:00:00,185.42,161
22,23,128456,Abdelhamid El Kaoutari,188145,1990-03-17 00:00:00,180.34,161
23,24,42664,Abdelkader Ghezzal,178063,1984-12-05 00:00:00,182.88,172
24,25,425950,Abdellah Zoubir,212934,1991-12-05 00:00:00,180.34,161
25,26,38423,Abdelmajid Oulmers,52782,1978-09-12 00:00:00,172.72,143
26,27,3264,Abdelmalek Cherrad,51868,1981-01-14 00:00:00,185.42,165
27,28,467485,Abdelmalek El Hasnaoui,209399,1994-02-09 00:00:00,180.34,159
28,29,306735,Abdelouahed Chakhsi,210504,1986-10-01 00:00:00,182.88,170
29,30,41659,Abderrazak Jadid,149241,1983-06-01 00:00:00,177.80,157
...,...,...,...,...,...,...,...
11030,11046,244155,Zezinho,212639,1992-09-23 00:00:00,175.26,161
11031,11047,19696,Zhi Zheng,158293,1980-08-20 00:00:00,180.34,165
11032,11048,290868,Zhi-Gin Lam,206209,1991-06-04 00:00:00,175.26,146
11033,11049,169594,Zie Diabate,207780,1989-03-02 00:00:00,177.80,143
11034,11050,244953,Ziggy Gordon,223263,1993-04-23 00:00:00,180.34,170
11035,11051,200607,Ziguy Badibanga,195862,1991-11-26 00:00:00,172.72,154
11036,11052,642618,Zinedine Machach,228821,1996-01-05 00:00:00,185.42,163
11037,11053,277772,Zinho Gano,204227,1993-10-13 00:00:00,198.12,205
11038,11054,246332,Ziri Hammar,202751,1992-07-25 00:00:00,180.34,163
11039,11055,532766,Zizo,222537,1996-01-10 00:00:00,175.26,148
11040,11056,27305,Zlatan Bajramovic,31667,1979-08-12 00:00:00,182.88,174
11041,11057,35724,Zlatan Ibrahimovic,41236,1981-10-03 00:00:00,195.58,209
11042,11058,12574,Zlatan Ljubijankic,176103,1983-12-15 00:00:00,185.42,176
11043,11059,39494,Zlatko Dedic,141111,1984-10-05 00:00:00,182.88,170
11044,11060,17233,Zlatko Janjic,188405,1986-05-07 00:00:00,187.96,183
11045,11061,42860,Zlatko Junuzovic,173474,1987-09-26 00:00:00,172.72,152
11046,11062,37128,Zola Matumona,158142,1981-11-26 00:00:00,165.10,143
11047,11063,24737,Zoltan Gera,137089,1979-04-22 00:00:00,182.88,165
11048,11064,107281,Zoltan Stieber,179712,1988-10-16 00:00:00,175.26,148
11049,11065,39801,Zoltan Szelesi,157283,1981-11-22 00:00:00,182.88,176
11050,11066,491794,Zoran Josipovic,219943,1995-08-25 00:00:00,187.96,165
11051,11067,56929,Zoran Rendulic,188593,1984-05-22 00:00:00,190.50,179
11052,11068,99031,Zoran Tosic,105454,1987-04-28 00:00:00,170.18,157
11053,11069,192132,Zouhaier Dhaouadhi,195840,1988-01-01 00:00:00,180.34,159
11054,11070,282473,Zouhair Feddal,205705,1989-01-01 00:00:00,190.50,172
11055,11071,26357,Zoumana Camara,2488,1979-04-03 00:00:00,182.88,168
11056,11072,111182,Zsolt Laczko,164680,1986-12-18 00:00:00,182.88,176
11057,11073,36491,Zsolt Low,111191,1979-04-29 00:00:00,180.34,154
11058,11074,35506,Zurab Khizanishvili,47058,1981-10-06 00:00:00,185.42,172
11059,11075,39902,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

In [12]:
pd.read_sql("select * from twitter;",con)

,Player_api_id,User_Name,Screen_Name,Tweet_created,Retweeted,Favourited,Location,Time_Zone,Geo,Text,Favourites_Count,Friends_Count,Followers_Count,Statuses_Count,Hashtags,URL
0,213501,Lynx,LynxApk,2018-04-22 23:36:32,False,False,Meme Land,Mexico City,None,RT @kingzorro81: Last weekend we got hit with ...,114,93,492,146,None,[]
1,213501,lbhkr,LBHKRRecords,2018-04-22 22:42:53,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,1163,1432,127,4035,None,[]
2,213501,Emmanuel Olabayo,bayonuels,2018-04-22 22:30:35,False,False,"Lagos state, Nigeria.",None,None,In a season that had bigger money moves by #Lu...,931,701,424,1399,Lukaku,"[{'url': 'https://t.co/KUakEbyvx4', 'expanded_..."
3,213501,Andrea Fabris,andreafabris96,2018-04-22 21:56:45,False,False,Verderio,Rome,None,Olivier #Giroud e Alvaro #Morata portano il Ch...,23730,1523,538,34752,Giroud,"[{'url': 'https://t.co/UCTBsylBjT', 'expanded_..."
4,213501,Harvey Emby,harveyemby10,2018-04-22 21:40:42,False,False,,None,None,"Great atmosphere at Wembley today, fans were g...",88,179,22,164,None,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_..."
5,213501,Harvey Emby,harveyemby10,2018-04-22 21:38:20,False,False,,None,None,Just to say Giroud’s goal today should be give...,88,179,22,164,None,"[{'url': 'https://t.co/wVVbYkHoUr', 'expanded_..."
6,213501,"Mary ATP, Arsenal 🇸🇳",mms_soumare,2018-04-22 21:20:01,False,False,Senegal,None,None,13 buts en #PL c’est 2 de + que #Morata et “qu...,602,1331,408,273,PL,"[{'url': 'https://t.co/XpLDpwAsql', 'expanded_..."
7,213501,SHOWY!,CamiloR531,2018-04-22 21:13:03,False,False,Colombia,Bogota,None,"ASÍ VIVE ÁLVARO MORATA, CONOCE A SU HERMOSA MU...",59,408,142,5861,Manchester,"[{'url': 'https://t.co/n33ucgNsZC', 'expanded_..."
8,213501,Jordi Garcia Serna,jordigarciatv,2018-04-22 20:36:41,False,False,,Pacific Time (US & Canada),None,Giroud y #Morata guían al #Chelsea a la final ...,100,39344,42847,7362,Morata,"[{'url': 'https://t.co/YASE8rSheJ', 'expanded_..."
9,213501,malik adams,malikadams1298,2018-04-22 20:15:12,False,False,"Toronto, Ontario",None,None,RT @kingzorro81: Last weekend we got hit with ...,719,971,41,1394,None,[]
10,213501,yunghova,hovie1234,2018-04-22 20:10:07,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,36,22,4,156,None,[]
11,213501,kaito,kaito_z12,2018-04-22 20:06:37,False,False,"Makassar, Indonesia",None,None,RT @kingzorro81: Last weekend we got hit with ...,72,557,22,302,None,[]
12,213501,marzok zeze,ZezeMarzok,2018-04-22 19:57:02,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,64,412,7,142,None,[]
13,213501,Taye6️⃣🔥,6thFlameRebel_,2018-04-22 19:54:15,False,False,Louisiana,None,None,RT @kingzorro81: Last weekend we got hit with ...,828,13,696,1241,None,[]
14,213501,Alva Starr,SplendorNatalie,2018-04-22 19:48:07,False,False,ESPAÑA,Athens,None,RT @Nataxab3: Me acuerdo cuando decían q Españ...,7546,510,651,34547,Morata,[]
15,213501,Raichel,crypto_chechi,2018-04-22 19:39:56,False,False,"San Jose, CA",None,None,RT @kingzorro81: Last weekend we got hit with ...,100,240,211,136,None,[]
16,213501,karwankurd,karwankurd4,2018-04-22 19:33:50,False,False,Iraq,Hawaii,None,RT @kingzorro81: Last weekend we got hit with ...,284,1671,130,1483,None,[]
17,213501,Agentianonimi.com,AgentiAnonimi,2018-04-22 19:24:52,False,False,"Milano, Lombardia",Rome,None,#FACUP: #Giroud e #Morata portano il #Chelsea ...,6938,424,4977,27293,FACUP,"[{'url': 'https://t.co/daJME93pgT', 'expanded_..."
18,213501,Transfermarkt.pl,TMpl_news,2018-04-22 19:20:01,False,False,,None,None,Chelsea rywalem Manchesteru United w finale ht...,0,12,2888,20138,transfermarkt,"[{'url': 'https://t.co/Q1c4oJb2ie', 'expanded_..."
19,213501,Premier League en español,PremierIeagueES,2018-04-22 19:10:49,False,False,,Buenos Aires,None,#FACup\n\n#Chelsea 2 - 0 #Southampton\n\n46' #...,286,33,3195,833,FACup,[]
20,107417,Ariel Montecinos Y.,arielmontecinos,2018-04-22 23:03:11,False,False,"Santiago, Chile",Santiago,None,"@Goal_en_espanol @ChelseaFC_Sp, cuando vi los ...",570,201,161,5471,Chelsea,"[{'url': 'https://t.co/GQLsTAirdA', 'expanded_..."
21,107417,Eshk13,Eshk_chelsea,2018-04-22 22:06:22,False,False,kurdistan,Pacific Time (US & Canada),None,@hazardeden10 ❤👏👊 \n.\n.\n#chelsea #cfc #hazar...,1108,221,27,27,chelsea,[]
22,107417,And Smith Must Score,AndSmithMustSc1,2018-04-22 22:05:35,False,False,next: tbc,Casablanca,None,RT @AndSmithMustSc1: Although Citeh have strol...,347,984,493,3104,Salah,[]
23,107417,MC,mchino141731,2018-04-22 21:48:36,False,False,,None,None,@zazzatweet @pisto_gol @FabRavezzani Su #Dybal...,1,38,3,99,Dybala,"[{'url': 'https://t.co/dKwRtqbIsq', 'expanded_..."
24,107417,Dave Heasman,daveheez,2018-04-22 21:43:13,False,False,London,London,None,RT @jakeheasman: He can frustrate the life out...,1621,313,277,11409,None,[]
25,107417,Harvey Emby,harveyemby10,2018-04-22 21:40:42,False,False,,None,None,"Great atmosphere at Wembley today, fans were g...",88,179,22,164,None,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_..."
26,107417,AJ,ajaybhatus,2018-04-22 20:54:25,False,False,,None,None,RT @LalitAmbardar: @PiyushGoyalOffc Gaping hol...,3018,600,309,8092,Hazard,[]
27,107417,Thomas Hoskins ⭐,RealTomHoskins,2018-04-22 20:49:02,False,False,"Weston-super-Mare, England",London,None,RT @jakeheasman: He can frustrate the life out...,43037,868,1120,130858,None,[]
28,107417,Jake Heasman,jakeheasman,2018-04-22 20:42:08,False,False,"London, England",London,None,"He can frustrate the life out of me, but games...",3843,1056,1060,11057,None,"[{'url': 'https://t.co/snmiVp16Dc', 'expanded_..."
29,107417,chelseanews24,chelseanews24h,2018-04-22 20:14:16,False,False,London,London,None,"#Hazard, satisfied for the game and results, c...",8,259,466,10587,Hazard,"[{'url': 'https://t.co/q7wNVvbdIM', 'expanded_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,30613,Fredrik Nylund,fredomdet,2018-04-22 14:12:15,False,False,,None,None,Can #Fàbregas find that cutting edge pass agai...,17890,262,201,10543,Fàbregas,[]
140,30613,The Kitman ⚽️👕,TheKitmanUK,2018-04-22 07:30:21,False,False,"Bristol, England",London,None,Checkout this Arsenal Home Shirt 2008-10 Fabre...,11548,5001,2697,30138,Arsenal,"[{'url': 'https://t.co/X5MCBAbJyN', 'expanded_..."
141,478393,BLANCHARD,loblanchard13,2018-04-22 22:25:31,False,False,Vaucluse,None,None,RT @JeanLombardozzi: La Une de @laprovence des...,803,260,739,3076,OM,[]
142,478393,Quentin Gil,GILQuentin1,2018-04-22 21:53:32,False,False,France,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,10,453,146,2099,OM,[]
143,478393,OMarseglia,OMarseglia13,2018-04-22 21:29:30,False,False,"Marseille, France",Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,3558,616,126,2642,OM,[]
144,478393,Michael,Michom15,2018-04-22 20:22:44,False,False,,Brussels,None,RT @JeanLombardozzi: La Une de @laprovence des...,1434,365,38,1312,OM,[]
145,478393,Alexomile,alexomile,2018-04-22 20:18:08,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,4,126,572,41464,OM,[]
146,478393,Adrien,Marseillais3_1,2018-04-22 19:54:06,False,False,"Nord, Nord-Pas-de-Calais",Pacific Time (US & Canada),None,RT @JeanLombardozzi: La Une de @laprovence des...,54,181,12,75,OM,[]
147,478393,olympienne13,vanessahidalg13,2018-04-22 19:53:57,False,False,"Tourlaville, France",None,None,RT @JeanLombardozzi: La Une de @laprovence des...,2897,956,68,2782,OM,[]
148,478393,Pastaga,PastagaDST,2018-04-22 19:52:28,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,9986,489,860,33234,OM,[]
149,478393,Alexandre Jacquin,AJac13,2018-04-22 19:51:18,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,6060,834,13261,9727,OM,[]
150,478393,DIASSS,Diasss_13,2018-04-22 19:42:33,False,False,Virage Sud,None,None,RT @JeanLombardozzi: La Une de @laprovence des...,20807,363,693,17766,OM,[]
151,478393,#TeamOM,JrmyAh,2018-04-22 19:41:44,False,False,"Marseille, France",London,None,RT @JeanLombardozzi: La Une de @laprovence des...,26980,341,734,52872,OM,[]
152,478393,Pattyn,PattynPatrick13,2018-04-22 19:37:43,False,False,"Marseille, France",None,None,RT @JeanLombardozzi: La Une de @laprovence des...,6346,756,428,4869,OM,[]
153,478393,Jérémy Tordjman,Jay_Tordjman,2018-04-22 19:36:09,False,False,"Marseille, et ailleurs...",Pacific Time (US & Canada),None,RT @JeanLombardozzi: La Une de @laprovence des...,338,721,4648,7606,OM,[]
154,478393,Jean Lombardozzi,JeanLombardozzi,2018-04-22 19:34:46,False,False,Marseille,None,None,La Une de @laprovence des Sports ce lundi 23 a...,86,78,775,1509,OM,"[{'url': 'https://t.co/VpZ1degXKM', 'expanded_..."
155,478393,WAHOME,wahome__,2018-04-22 18:52:58,False,False,Kenya,None,None,Bakayoko has improved !!!👏👏\nNext year he'll b...,2391,1174,1531,823,Bakayoko,[]
156,478393,Ricky nelly,Rickkynelly,2018-04-22 18:50:23,False,False,Abuja Nigeria,None,None,Seems like #Willian was not angry for being su...,7668,592,141,990,Willian,"[{'url': 'https://t.co/OM4Esj6zWD', 'expanded_..."
157,478393,Tzar,Tzarrahlapane,2018-04-22 17:19:32,False,False,Tshwane,None,None,@ChelseaFC Sell #Bakayoko and sign #Nzonzi,642,412,85,1243,Bakayoko,[]
158,478393,Excelsior! ⚽ 🎾,PhilPlanter,2018-04-22 15:44:33,False,False,Galt's Gulch,Quito,None,#Bakayoko makes the simple things seem excruci...,743,2952,1074,8896,Bakayoko,[]
159,478393,Sohaib Khan,KhanGaming_,2018-04-22 15:29:42,False,False,,Casablanca,None,What does #Bakayoko bring??,2712,63,231,1907,Bakayoko,[]
160,478393,Mark Johnson,majohnsonesq,2018-04-22 15:27:24,False,False,Here,America/New_York,None,RT @PhilPlanter: #Conte substitutes #Willian f...,173,85,22,360,Conte,[]
161,23783,Laurenz Vescoli,Laus1507,2018-04-22 21:55:26,False,False,"Innsbruck, Austria",Belgrade,None,Strong against Austin in the air and no mistak...,3571,481,1470,4682,cfc,[]
162,23783,AW,agmow2012,2018-04-22 09:35:09,False,False,"London, England",Amsterdam,None,@OTD_PL @therealstevenpi @ManUtd @Everton @les...,740,329,28,2106,efc,[]
163,23783,Kimberly,candypie22,2018-04-22 01:24:30,False,False,Asgard,None,None,RT @GyspsyLoveserie: @candypie22 @LethalWeapon...,139981,3663,2512,195823,None,[]
164,23783,Kimberly,candypie22,2018-04-22 01:24:13,False,False,Asgard,None,None,RT @GyspsyLoveserie: @Mizcrea @candypie22 @Let...,139981,3663,2512,195823,None,[]
165,23783,Laurenz Vescoli,Laus1507,2018-04-22 21:55:26,False,False,"Innsbruck, Austria",Belgrade,None,Strong against Austin in the air and no mistak...,3571,481,1470,4682,cfc,[]
166,23783,AW,agmow2012,2018-04-22 09:35:09,False,False,"London, England",Amsterdam,None,@OTD_PL @therealstevenpi @ManUtd @Everton @les...,740,329,28,2106,efc,[]
167,23783,Kimberly,candypie22,2018-04-22 01:24:30,False,False,Asgard,None,None,RT @GyspsyLoveserie: @candypie22 @LethalWeapon...,139981,3663,2512,195823,None,[]
168,23783,Kimberly,candypie22,2018-04-22 01:24:13,False,False,Asgard,None,None,RT @GyspsyLoveserie: @Mizcrea @candypie22 @Let...,139981,3663,2512,195823,None,[]

In [16]:
dftest = pd.read_sql("select player_name, user_name, screen_name, tweet_created, retweeted, favourited, location, time_zone, geo, text, favourites_count, friends_count, followers_count, Statuses_Count, hashtags, URL from twitter left join player on twitter.Player_api_id = player.player_api_id;",con)

dftest

,player_name,User_Name,Screen_Name,Tweet_created,Retweeted,Favourited,Location,Time_Zone,Geo,Text,Favourites_Count,Friends_Count,Followers_Count,Statuses_Count,Hashtags,URL
0,Alvaro Morata,Lynx,LynxApk,2018-04-22 23:36:32,False,False,Meme Land,Mexico City,None,RT @kingzorro81: Last weekend we got hit with ...,114,93,492,146,None,[]
1,Alvaro Morata,lbhkr,LBHKRRecords,2018-04-22 22:42:53,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,1163,1432,127,4035,None,[]
2,Alvaro Morata,Emmanuel Olabayo,bayonuels,2018-04-22 22:30:35,False,False,"Lagos state, Nigeria.",None,None,In a season that had bigger money moves by #Lu...,931,701,424,1399,Lukaku,"[{'url': 'https://t.co/KUakEbyvx4', 'expanded_..."
3,Alvaro Morata,Andrea Fabris,andreafabris96,2018-04-22 21:56:45,False,False,Verderio,Rome,None,Olivier #Giroud e Alvaro #Morata portano il Ch...,23730,1523,538,34752,Giroud,"[{'url': 'https://t.co/UCTBsylBjT', 'expanded_..."
4,Alvaro Morata,Harvey Emby,harveyemby10,2018-04-22 21:40:42,False,False,,None,None,"Great atmosphere at Wembley today, fans were g...",88,179,22,164,None,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_..."
5,Alvaro Morata,Harvey Emby,harveyemby10,2018-04-22 21:38:20,False,False,,None,None,Just to say Giroud’s goal today should be give...,88,179,22,164,None,"[{'url': 'https://t.co/wVVbYkHoUr', 'expanded_..."
6,Alvaro Morata,"Mary ATP, Arsenal 🇸🇳",mms_soumare,2018-04-22 21:20:01,False,False,Senegal,None,None,13 buts en #PL c’est 2 de + que #Morata et “qu...,602,1331,408,273,PL,"[{'url': 'https://t.co/XpLDpwAsql', 'expanded_..."
7,Alvaro Morata,SHOWY!,CamiloR531,2018-04-22 21:13:03,False,False,Colombia,Bogota,None,"ASÍ VIVE ÁLVARO MORATA, CONOCE A SU HERMOSA MU...",59,408,142,5861,Manchester,"[{'url': 'https://t.co/n33ucgNsZC', 'expanded_..."
8,Alvaro Morata,Jordi Garcia Serna,jordigarciatv,2018-04-22 20:36:41,False,False,,Pacific Time (US & Canada),None,Giroud y #Morata guían al #Chelsea a la final ...,100,39344,42847,7362,Morata,"[{'url': 'https://t.co/YASE8rSheJ', 'expanded_..."
9,Alvaro Morata,malik adams,malikadams1298,2018-04-22 20:15:12,False,False,"Toronto, Ontario",None,None,RT @kingzorro81: Last weekend we got hit with ...,719,971,41,1394,None,[]
10,Alvaro Morata,yunghova,hovie1234,2018-04-22 20:10:07,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,36,22,4,156,None,[]
11,Alvaro Morata,kaito,kaito_z12,2018-04-22 20:06:37,False,False,"Makassar, Indonesia",None,None,RT @kingzorro81: Last weekend we got hit with ...,72,557,22,302,None,[]
12,Alvaro Morata,marzok zeze,ZezeMarzok,2018-04-22 19:57:02,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,64,412,7,142,None,[]
13,Alvaro Morata,Taye6️⃣🔥,6thFlameRebel_,2018-04-22 19:54:15,False,False,Louisiana,None,None,RT @kingzorro81: Last weekend we got hit with ...,828,13,696,1241,None,[]
14,Alvaro Morata,Alva Starr,SplendorNatalie,2018-04-22 19:48:07,False,False,ESPAÑA,Athens,None,RT @Nataxab3: Me acuerdo cuando decían q Españ...,7546,510,651,34547,Morata,[]
15,Alvaro Morata,Raichel,crypto_chechi,2018-04-22 19:39:56,False,False,"San Jose, CA",None,None,RT @kingzorro81: Last weekend we got hit with ...,100,240,211,136,None,[]
16,Alvaro Morata,karwankurd,karwankurd4,2018-04-22 19:33:50,False,False,Iraq,Hawaii,None,RT @kingzorro81: Last weekend we got hit with ...,284,1671,130,1483,None,[]
17,Alvaro Morata,Agentianonimi.com,AgentiAnonimi,2018-04-22 19:24:52,False,False,"Milano, Lombardia",Rome,None,#FACUP: #Giroud e #Morata portano il #Chelsea ...,6938,424,4977,27293,FACUP,"[{'url': 'https://t.co/daJME93pgT', 'expanded_..."
18,Alvaro Morata,Transfermarkt.pl,TMpl_news,2018-04-22 19:20:01,False,False,,None,None,Chelsea rywalem Manchesteru United w finale ht...,0,12,2888,20138,transfermarkt,"[{'url': 'https://t.co/Q1c4oJb2ie', 'expanded_..."
19,Alvaro Morata,Premier League en español,PremierIeagueES,2018-04-22 19:10:49,False,False,,Buenos Aires,None,#FACup\n\n#Chelsea 2 - 0 #Southampton\n\n46' #...,286,33,3195,833,FACup,[]
20,Eden Hazard,Ariel Montecinos Y.,arielmontecinos,2018-04-22 23:03:11,False,False,"Santiago, Chile",Santiago,None,"@Goal_en_espanol @ChelseaFC_Sp, cuando vi los ...",570,201,161,5471,Chelsea,"[{'url': 'https://t.co/GQLsTAirdA', 'expanded_..."
21,Eden Hazard,Eshk13,Eshk_chelsea,2018-04-22 22:06:22,False,False,kurdistan,Pacific Time (US & Canada),None,@hazardeden10 ❤👏👊 \n.\n.\n#chelsea #cfc #hazar...,1108,221,27,27,chelsea,[]
22,Eden Hazard,And Smith Must Score,AndSmithMustSc1,2018-04-22 22:05:35,False,False,next: tbc,Casablanca,None,RT @AndSmithMustSc1: Although Citeh have strol...,347,984,493,3104,Salah,[]
23,Eden Hazard,MC,mchino141731,2018-04-22 21:48:36,False,False,,None,None,@zazzatweet @pisto_gol @FabRavezzani Su #Dybal...,1,38,3,99,Dybala,"[{'url': 'https://t.co/dKwRtqbIsq', 'expanded_..."
24,Eden Hazard,Dave Heasman,daveheez,2018-04-22 21:43:13,False,False,London,London,None,RT @jakeheasman: He can frustrate the life out...,1621,313,277,11409,None,[]
25,Eden Hazard,Harvey Emby,harveyemby10,2018-04-22 21:40:42,False,False,,None,None,"Great atmosphere at Wembley today, fans were g...",88,179,22,164,None,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_..."
26,Eden Hazard,AJ,ajaybhatus,2018-04-22 20:54:25,False,False,,None,None,RT @LalitAmbardar: @PiyushGoyalOffc Gaping hol...,3018,600,309,8092,Hazard,[]
27,Eden Hazard,Thomas Hoskins ⭐,RealTomHoskins,2018-04-22 20:49:02,False,False,"Weston-super-Mare, England",London,None,RT @jakeheasman: He can frustrate the life out...,43037,868,1120,130858,None,[]
28,Eden Hazard,Jake Heasman,jakeheasman,2018-04-22 20:42:08,False,False,"London, England",London,None,"He can frustrate the life out of me, but games...",3843,1056,1060,11057,None,"[{'url': 'https://t.co/snmiVp16Dc', 'expanded_..."
29,Eden Hazard,chelseanews24,chelseanews24h,2018-04-22 20:14:16,False,False,London,London,None,"#Hazard, satisfied for the game and results, c...",8,259,466,10587,Hazard,"[{'url': 'https://t.co/q7wNVvbdIM', 'expanded_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,Cesc Fabregas,Fredrik Nylund,fredomdet,2018-04-22 14:12:15,False,False,,None,None,Can #Fàbregas find that cutting edge pass agai...,17890,262,201,10543,Fàbregas,[]
140,Cesc Fabregas,The Kitman ⚽️👕,TheKitmanUK,2018-04-22 07:30:21,False,False,"Bristol, England",London,None,Checkout this Arsenal Home Shirt 2008-10 Fabre...,11548,5001,2697,30138,Arsenal,"[{'url': 'https://t.co/X5MCBAbJyN', 'expanded_..."
141,Tiemoue Bakayoko,BLANCHARD,loblanchard13,2018-04-22 22:25:31,False,False,Vaucluse,None,None,RT @JeanLombardozzi: La Une de @laprovence des...,803,260,739,3076,OM,[]
142,Tiemoue Bakayoko,Quentin Gil,GILQuentin1,2018-04-22 21:53:32,False,False,France,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,10,453,146,2099,OM,[]
143,Tiemoue Bakayoko,OMarseglia,OMarseglia13,2018-04-22 21:29:30,False,False,"Marseille, France",Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,3558,616,126,2642,OM,[]
144,Tiemoue Bakayoko,Michael,Michom15,2018-04-22 20:22:44,False,False,,Brussels,None,RT @JeanLombardozzi: La Une de @laprovence des...,1434,365,38,1312,OM,[]
145,Tiemoue Bakayoko,Alexomile,alexomile,2018-04-22 20:18:08,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,4,126,572,41464,OM,[]
146,Tiemoue Bakayoko,Adrien,Marseillais3_1,2018-04-22 19:54:06,False,False,"Nord, Nord-Pas-de-Calais",Pacific Time (US & Canada),None,RT @JeanLombardozzi: La Une de @laprovence des...,54,181,12,75,OM,[]
147,Tiemoue Bakayoko,olympienne13,vanessahidalg13,2018-04-22 19:53:57,False,False,"Tourlaville, France",None,None,RT @JeanLombardozzi: La Une de @laprovence des...,2897,956,68,2782,OM,[]
148,Tiemoue Bakayoko,Pastaga,PastagaDST,2018-04-22 19:52:28,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,9986,489,860,33234,OM,[]
149,Tiemoue Bakayoko,Alexandre Jacquin,AJac13,2018-04-22 19:51:18,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,6060,834,13261,9727,OM,[]
150,Tiemoue Bakayoko,DIASSS,Diasss_13,2018-04-22 19:42:33,False,False,Virage Sud,None,None,RT @JeanLombardozzi: La Une de @laprovence des...,20807,363,693,17766,OM,[]
151,Tiemoue Bakayoko,#TeamOM,JrmyAh,2018-04-22 19:41:44,False,False,"Marseille, France",London,None,RT @JeanLombardozzi: La Une de @laprovence des...,26980,341,734,52872,OM,[]
152,Tiemoue Bakayoko,Pattyn,PattynPatrick13,2018-04-22 19:37:43,False,False,"Marseille, France",None,None,RT @JeanLombardozzi: La Une de @laprovence des...,6346,756,428,4869,OM,[]
153,Tiemoue Bakayoko,Jérémy Tordjman,Jay_Tordjman,2018-04-22 19:36:09,False,False,"Marseille, et ailleurs...",Pacific Time (US & Canada),None,RT @JeanLombardozzi: La Une de @laprovence des...,338,721,4648,7606,OM,[]
154,Tiemoue Bakayoko,Jean Lombardozzi,JeanLombardozzi,2018-04-22 19:34:46,False,False,Marseille,None,None,La Une de @laprovence des Sports ce lundi 23 a...,86,78,775,1509,OM,"[{'url': 'https://t.co/VpZ1degXKM', 'expanded_..."
155,Tiemoue Bakayoko,WAHOME,wahome__,2018-04-22 18:52:58,False,False,Kenya,None,None,Bakayoko has improved !!!👏👏\nNext year he'll b...,2391,1174,1531,823,Bakayoko,[]
156,Tiemoue Bakayoko,Ricky nelly,Rickkynelly,2018-04-22 18:50:23,False,False,Abuja Nigeria,None,None,Seems like #Willian was not angry for being su...,7668,592,141,990,Willian,"[{'url': 'https://t.co/OM4Esj6zWD', 'expanded_..."
157,Tiemoue Bakayoko,Tzar,Tzarrahlapane,2018-04-22 17:19:32,False,False,Tshwane,None,None,@ChelseaFC Sell #Bakayoko and sign #Nzonzi,642,412,85,1243,Bakayoko,[]
158,Tiemoue Bakayoko,Excelsior! ⚽ 🎾,PhilPlanter,2018-04-22 15:44:33,False,False,Galt's Gulch,Quito,None,#Bakayoko makes the simple things seem excruci...,743,2952,1074,8896,Bakayoko,[]
159,Tiemoue Bakayoko,Sohaib Khan,KhanGaming_,2018-04-22 15:29:42,False,False,,Casablanca,None,What does #Bakayoko bring??,2712,63,231,1907,Bakayoko,[]
160,Tiemoue Bakayoko,Mark Johnson,majohnsonesq,2018-04-22 15:27:24,False,False,Here,America/New_York,None,RT @PhilPlanter: #Conte substitutes #Willian f...,173,85,22,360,Conte,[]
161,Gary Cahill,Laurenz Vescoli,Laus1507,2018-04-22 21:55:26,False,False,"Innsbruck, Austria",Belgrade,None,Strong against Austin in the air and no mistak...,3571,481,1470,4682,cfc,[]
162,Gary Cahill,AW,agmow2012,2018-04-22 09:35:09,False,False,"London, England",Amsterdam,None,@OTD_PL @therealstevenpi @ManUtd @Everton @les...,740,329,28,2106,efc,[]
163,Gary Cahill,Kimberly,candypie22,2018-04-22 01:24:30,False,False,Asgard,None,None,RT @GyspsyLoveserie: @candypie22 @LethalWeapon...,139981,3663,2512,195823,None,[]
164,Gary Cahill,Kimberly,candypie22,2018-04-22 01:24:13,False,False,Asgard,None,None,RT @GyspsyLoveserie: @Mizcrea @candypie22 @Let...,139981,3663,2512,195823,None,[]
165,Gary Cahill,Laurenz Vescoli,Laus1507,2018-04-22 21:55:26,False,False,"Innsbruck, Austria",Belgrade,None,Strong against Austin in the air and no mistak...,3571,481,1470,4682,cfc,[]
166,Gary Cahill,AW,agmow2012,2018-04-22 09:35:09,False,False,"London, England",Amsterdam,None,@OTD_PL @therealstevenpi @ManUtd @Everton @les...,740,329,28,2106,efc,[]
167,Gary Cahill,Kimberly,candypie22,2018-04-22 01:24:30,False,False,Asgard,None,None,RT @GyspsyLoveserie: @candypie22 @LethalWeapon...,139981,3663,2512,195823,None,[]
168,Gary Cahill,Kimberly,candypie22,2018-04-22 01:24:13,False,False,Asgard,None,None,RT @GyspsyLoveserie: @Mizcrea @candypie22 @Let...,139981,3663,2512,195823,None,[]

In [ ]:
dftest.to_csv('player.csv');

In [17]:
pd.read_sql("select * FROM facebook;",con)

,Team_api_id,Fan_Count,Likes,Shares,Comments,Messages
0,10260,73698717,8962,58,65,Four games left to impress!
1,10260,73698717,29428,1852,833,Cristiano Ronaldo ⚽️⚽️\nWayne Rooney ⚽️⚽️\nDim...
2,10260,73698717,16919,604,209,Jesse Lingard’s solo effort against Watford wo...
3,10260,73698717,11025,226,76,Awesome from Uber 👏\n\nBringing fans closer to...
4,10260,73698717,3300,43,16,None
5,10260,73698696,8976,58,65,Four games left to impress!
6,10260,73698696,29447,1854,833,Cristiano Ronaldo ⚽️⚽️\nWayne Rooney ⚽️⚽️\nDim...
7,10260,73698696,16928,604,210,Jesse Lingard’s solo effort against Watford wo...
8,10260,73698696,11049,226,76,Awesome from Uber 👏\n\nBringing fans closer to...
9,10260,73698696,3301,43,16,None
10,10260,22872,0,0,0,TOP 18 ● MANCHESTER UNITED GOALS ●
11,10260,22872,7,0,0,Eric Cantona no.1⃣ goal for Manchester United
12,10260,22872,4,0,0,Eric Bailly & Zlatan Ibrahimovich
13,10260,22872,5,0,0,Vintage Cristiano Ronaldo against Everton
14,10260,22872,4,0,0,Fucking Kyle Walker
15,10260,22872,3,0,0,Cristiano Ronaldo surprises a kid on a Madrid'...
16,10260,22872,3,0,0,None
17,10260,22872,5,0,0,"Bienvenue, Eric! 👑 King Cantona arrived at Old..."
18,10260,22872,5,0,0,None
19,10260,22872,4,0,0,None
20,10260,22872,3,0,0,None
21,10260,22872,5,0,0,None
22,10260,107872907,46629,1685,550,⚽💫🎥 #APorLa132\nRelive our victory in Munich a...
23,10260,107872907,94248,3748,1233,🙌 Marcelo M12\n⚽ GOALS VS:\n🇩🇪 Bayern Munich\n...
24,10260,107872907,172149,16609,2544,FC Bayern Munich 1-2 Real Madrid C.F.\n⚽ 75' M...
25,10260,107872907,481240,114662,13056,🏁 FT: FC Bayern Munich1-2 Real Madrid C.F.\n(K...
26,10260,107872907,132990,14662,3429,📝 Real Madrid C.F. XI 🆚 FC Bayern Munich\n#APo...
27,10260,107872907,69341,8330,19231,🚍➡🏟 #RMUCL 🔴 LIVE\nWatch our arrival at the Al...
28,10260,107872907,48890,4436,834,None
29,10260,107872907,105040,16356,2418,🙌 IT'S MATCHDAY! | ¡DÍA DE PARTIDO! 🙌\n🆚 FC Ba...
...,...,...,...,...,...,...
75,8634,103190687,76517,2156,680,🙌👏 Barça Fans are the best! 💙❤️
76,8634,103190687,25385,396,185,Everything is about to change between Leo Mess...
77,8634,103190687,47669,3752,556,"🏆👏 Congratulations, FCB Masia - UEFA Youth Lea..."
78,8634,103190687,60983,4501,358,🎥 All the best behind-the-scenes bits from #Co...
79,8634,103190687,118820,3545,1211,🔙 23/04/2017\n📍 Bernabeu\n⚽️ Real Madrid 2️⃣-3...
80,8634,103190687,155086,6284,863,🏆 #MondayMotivation\n🔵🔴 #Copa30
81,8634,103190687,63647,2879,493,🔥⚽️🙌 FCB Masia
82,8634,103190687,28556,1479,311,🐲🌹 Happy #SantJordi's Day! Do you know the sto...
83,8634,103190687,60744,1305,268,👀🏆 The other side of #Copa30! 🔵🔴\n👀🏆 ¡La otra ...
84,8634,103190687,28692,703,203,🔊 Turn up the volume! This is how we experien...
85,8455,47830931,10641,575,233,In 7️⃣th heaven! 🔥\n\nThe Blues beat Stoke 7-0...
86,8455,47830931,49,1,2,Yokohama is bringing two youth soccer players ...
87,8455,47830931,94118,11433,3694,6️⃣ years ago today!
88,8455,47830931,12251,78,109,Our Under-19s’ return to the UEFA Youth League...
89,8455,47830931,9213,229,75,🎥 When you give Callum Hudson-Odoi the camera ...
90,8455,47830931,55816,5729,1986,Olivier Giroud brought his love of slalom skii...
91,8455,47830931,15936,351,190,"'We have the chance to get a trophy, an import..."
92,8455,47830931,15549,333,162,'I'm very proud' 👊\n\nThe thoughts of Olivier ...
93,8455,47830931,8704,448,87,"Good luck, Chelsea Ladies Football Club! 🙌"
94,8455,47830931,32727,715,311,"FA Cup final, here we come! 💪"
95,8455,47830931,3559,63,362,Who was your man of the match today? 🤔
96,8455,47830931,25914,574,201,Our goal scorers today! ⚽️⚽️\n\nWell played Ol...
97,8455,47830931,95558,10350,1529,We are in to the FA Cup final! 🙌
98,8455,47830931,42091,2234,557,MORATAAAA! 🙌\n\nInstant impact from Alvaro who...
99,8455,47830931,14264,144,123,Sub: Our goalscorer makes way and Alvaro Morat...
100,8455,47830931,10963,113,482,Antonio Conte makes his first change of the ga...
101,8455,47830931,31288,1622,491,WHAT A START TO THE SECOND HALF! 🔥\n\nThe Blue...
102,8455,47830931,9441,230,235,"The Blues have been on top but at halfway, it'..."
103,8455,47830931,9133,287,99,A man who has plenty of good Wembley memories ...
104,8455,47830931,9919,331,221,The warm-ups are underway at Wembley! 💪\n\nWha...

In [18]:
pd.read_sql("select * from team;",con)

,id,team_api_id,team_fifa_api_id,team_long_name,team_short_name
0,1,9987,673.0,KRC Genk,GEN
1,2,9993,675.0,Beerschot AC,BAC
2,3,10000,15005.0,SV Zulte-Waregem,ZUL
3,4,9994,2007.0,Sporting Lokeren,LOK
4,5,9984,1750.0,KSV Cercle Brugge,CEB
5,6,8635,229.0,RSC Anderlecht,AND
6,7,9991,674.0,KAA Gent,GEN
7,8,9998,1747.0,RAEC Mons,MON
8,9,7947,NaN,FCV Dender EH,DEN
9,10,9985,232.0,Standard de Liège,STL
10,11,8203,110724.0,KV Mechelen,MEC
11,12,8342,231.0,Club Brugge KV,CLB
12,13,9999,546.0,KSV Roeselare,ROS
13,14,8571,100081.0,KV Kortrijk,KOR
14,15,4049,NaN,Tubize,TUB
15,16,9996,111560.0,Royal Excel Mouscron,MOU
16,17,10001,681.0,KVC Westerlo,WES
17,18,9986,670.0,Sporting Charleroi,CHA
18,614,9997,680.0,Sint-Truidense VV,STT
19,1034,9989,239.0,Lierse SK,LIE
20,1042,6351,2013.0,KAS Eupen,EUP
21,1513,1773,100087.0,Oud-Heverlee Leuven,O-H
22,2004,8475,110913.0,Waasland-Beveren,WAA
23,2476,8573,682.0,KV Oostende,OOS
24,2510,274581,111560.0,Royal Excel Mouscron,MOP
25,3457,10260,11.0,Manchester United,MUN
26,3458,10261,13.0,Newcastle United,NEW
27,3459,9825,1.0,Arsenal,ARS
28,3460,8659,109.0,West Bromwich Albion,WBA
29,3461,8472,106.0,Sunderland,SUN
...,...,...,...,...,...
269,43053,9906,240.0,Atlético Madrid,AMA
270,43054,9864,573.0,Málaga CF,MAL
271,43800,9868,1742.0,Xerez Club Deportivo,XER
272,43803,8394,244.0,Real Zaragoza,ZAR
273,43804,9867,260.0,CD Tenerife,TEN
274,44557,10278,100879.0,Hércules Club de Fútbol,HER
275,44565,8581,1853.0,Levante UD,LEV
276,44569,8560,457.0,Real Sociedad,SOC
277,45330,7878,110832.0,Granada CF,GRA
278,45333,8370,480.0,Rayo Vallecano,RAY
279,46087,9910,450.0,RC Celta de Vigo,CEL
280,46848,10268,468.0,Elche CF,ELC
281,47605,8372,467.0,SD Eibar,EIB
282,47612,7869,1867.0,Córdoba CF,COR
283,48358,8306,472.0,UD Las Palmas,LAS
284,49115,9956,322.0,Grasshopper Club Zürich,GRA
285,49116,6493,1714.0,AC Bellinzona,BEL
286,49117,10192,900.0,BSC Young Boys,YB
287,49118,9931,896.0,FC Basel,BAS
288,49119,9930,434.0,FC Aarau,AAR
289,49120,10179,110770.0,FC Sion,SIO
290,49121,10199,897.0,FC Luzern,LUZ
291,49122,9824,286.0,FC Vaduz,VAD
292,49123,7955,435.0,Neuchâtel Xamax,XAM
293,49124,10243,894.0,FC Zürich,ZUR
294,49479,10190,898.0,FC St. Gallen,GAL
295,49837,10191,1715.0,FC Thun,THU
296,50201,9777,324.0,Servette FC,SER
297,50204,7730,1862.0,FC Lausanne-Sports,LAU
298,51606,7896,NaN,Lugano,LUG

In [21]:
team =pd.read_sql("SELECT team_long_name, team_short_name, fan_count, likes, comments, shares, messages FROM facebook LEFT JOIN team ON facebook.Team_api_id = team.team_api_id;",con)

In [22]:
team.head()

,team_long_name,team_short_name,Fan_Count,Likes,Comments,Shares,Messages
0,Manchester United,MUN,73698717,8962,65,58,Four games left to impress!
1,Manchester United,MUN,73698717,29428,833,1852,Cristiano Ronaldo ⚽️⚽️\nWayne Rooney ⚽️⚽️\nDim...
2,Manchester United,MUN,73698717,16919,209,604,Jesse Lingard’s solo effort against Watford wo...
3,Manchester United,MUN,73698717,11025,76,226,Awesome from Uber 👏\n\nBringing fans closer to...
4,Manchester United,MUN,73698717,3300,16,43,None

In [ ]:
team.to_csv('team.csv')

## LICENSE

MIT License  

Copyright (c) 2018 Prathamesh Tari and Akshay Shinde

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.