We will be using Tweepy API. The API class provides access to the entire twitter RESTful API methods. Each method can accept various parameters and return responses.

In [7]:
import tweepy

ckey = "drSHfGFXcjznJo8YtyFFHBkAt"
csecret = "GVPc29f2GVbWlFsDtVcgPJm2ftVmAYB3uuch1g0rc6TpCIIEXb"
atoken = "968906797305204736-FBe84xjIvJmq3Y4PHQ6yPHcvZ9RigBh"
asecret = "A6njXzLXdE2R93roUkU4UACkCvQdWKGarHrrgyXPMAbQK"

OAUTH_KEYS = {'consumer_key':ckey, 'consumer_secret':csecret,
    'access_token_key':atoken, 'access_token_secret':asecret}
auth = tweepy.OAuthHandler(OAUTH_KEYS['consumer_key'], OAUTH_KEYS['consumer_secret'])
api = tweepy.API(auth)

In [8]:
import twitter
from twitter import* # pip install twitter
# Go to http://dev.twitter.com/apps/new to create an app and get values
# for these credentials, which you'll need to provide in place of these
# empty string values that are defined as placeholders.
# See https://dev.twitter.com/docs/auth/oauth for more information 
# on Twitter's OAuth implementation.

CONSUMER_KEY = 'drSHfGFXcjznJo8YtyFFHBkAt'
CONSUMER_SECRET = 'GVPc29f2GVbWlFsDtVcgPJm2ftVmAYB3uuch1g0rc6TpCIIEXb'
OAUTH_TOKEN = '968906797305204736-FBe84xjIvJmq3Y4PHQ6yPHcvZ9RigBh'
OAUTH_TOKEN_SECRET = 'A6njXzLXdE2R93roUkU4UACkCvQdWKGarHrrgyXPMAbQK'

auth = twitter.oauth.OAuth(OAUTH_TOKEN, OAUTH_TOKEN_SECRET,
                           CONSUMER_KEY, CONSUMER_SECRET)

twitter_api = twitter.Twitter(auth=auth)

# Nothing to see by displaying twitter_api except that it's now a
# defined variable

print(twitter_api)
database ='database.sqlite'

<twitter.api.Twitter object at 0x000002B444C63668>

In [9]:
import sqlite3
import pandas as pd
con = sqlite3.connect(database)
c=con.cursor()

Checking how to retrieve data using for loop to get multiple tweets and its information in one run

In [10]:
for tweet in tweepy.Cursor(api.search, q=('"Chelsea FC"'),since='2018-04-22', until='2018-04-23').items(20):

    print ("Name:", tweet.author.name)
    print ("Screen-name:", tweet.author.screen_name)
    print ("Tweet created:", tweet.created_at)
    print ("Retweeted:", tweet.retweeted)
    print ("Favourited:", tweet.favorited)
    print ("Location:", tweet.user.location.encode('utf8'))
    print ("Time-zone:", tweet.user.time_zone)
    print ("Geo:", tweet.geo)
    print ("Text:", tweet.text)
    print ("Favourites Count:", tweet.user.favourites_count)
    print ("Friends Count:", tweet.user.friends_count)
    print ("Followers Count:", tweet.user.followers_count)
    print ("Statuses Count:", tweet.user.statuses_count)
    
    try:
        print ("hashtags:", tweet.entities['hashtags'][0]['text'])
    except IndexError:
        print("hashtags: None" )
    print ("URL:", tweet.entities['urls'])
    print ("//////////////////")

Name: APRI YANTO SETIAWAN
Screen-name: apriiYS
Tweet created: 2018-04-22 23:59:47
Retweeted: False
Favourited: False
Location: b'BantarGebang/Pojokan Bekasi'
Time-zone: Bangkok
Geo: None
Text: RT @GOAL_ID: FT! Chelsea 2-0 Southampton! | LIVE: https://t.co/pkUrQAq2YK #MatchdayGoal

Final FA Cup akan mempertemukan Chelsea melawan Ma‚Ä¶
Favourites Count: 101
Friends Count: 495
Followers Count: 1405
Statuses Count: 19308
hashtags: MatchdayGoal
URL: [{'url': 'https://t.co/pkUrQAq2YK', 'expanded_url': 'http://bit.ly/2HkXbnw', 'display_url': 'bit.ly/2HkXbnw', 'indices': [50, 73]}]
//////////////////
Name: Raymound Seprizal A
Screen-name: raymounds
Tweet created: 2018-04-22 23:59:42
Retweeted: False
Favourited: False
Location: b''
Time-zone: Bangkok
Geo: None
Text: RT @GOAL_ID: FT! Chelsea 2-0 Southampton! | LIVE: https://t.co/pkUrQAq2YK #MatchdayGoal

Final FA Cup akan mempertemukan Chelsea melawan Ma‚Ä¶
Favourites Count: 89
Friends Count: 263
Followers Count: 245
Statuses Count: 15589
hashtags: MatchdayGoal
URL: [{'url': 'https://t.co/pkUrQAq2YK', 'expanded_url': 'http://bit.ly/2HkXbnw', 'display_url': 'bit.ly/2HkXbnw', 'indices': [50, 73]}]
//////////////////
Name: Jonathan Kydd
Screen-name: Jonathankydd
Tweet created: 2018-04-22 23:56:18
Retweeted: False
Favourited: False
Location: b"Shepherd's Bush"
Time-zone: London
Geo: None
Text: RT @ChelseaFanCast: Why the FA Cup is still Chelsea supporters first true love by @StamfordChidge for @Chelsea_FL https://t.co/zJAE1hAUib
Favourites Count: 25795
Friends Count: 2226
Followers Count: 3070
Statuses Count: 23652
hashtags: None
URL: [{'url': 'https://t.co/zJAE1hAUib', 'expanded_url': 'https://www.football.london/chelsea-fc/fixtures-results/chelsea-fans-southampton-fa-cup-14557354', 'display_url': 'football.london/chelsea-fc/fix‚Ä¶', 'indices': [114, 137]}]
//////////////////
Name: #AUGUST25/TEAMVIRGO
Screen-name: fadeyiolayinka
Tweet created: 2018-04-22 23:44:50
Retweeted: False
Favourited: False
Location: b'Lagos'
Time-zone: None
Geo: None
Text: RT @futballselect: üèÜ FA CUPFinal
üÜö Chelsea FC v Manchester United
üìÖ Saturday 19 May
üèüÔ∏è Wembley Stadium https://t.co/ElLilS4aod
Favourites Count: 2349
Friends Count: 9503
Followers Count: 10698
Statuses Count: 147515
hashtags: None
URL: []
//////////////////
Name: Chukwuemeka Onuabueke
Screen-name: COnuabueke
Tweet created: 2018-04-22 23:44:41
Retweeted: False
Favourited: False
Location: b'Lagos, Nigeria'
Time-zone: None
Geo: None
Text: @ChelseaFC Happy birthday to a #LEGEND that won everything with Chelsea FC. Such a nightmare to opposition attackers!
Favourites Count: 514
Friends Count: 146
Followers Count: 30
Statuses Count: 207
hashtags: LEGEND
URL: []
//////////////////
Name: Ina Al Maida
Screen-name: chelsiwonda
Tweet created: 2018-04-22 23:38:10
Retweeted: False
Favourited: False
Location: b'Singapore'
Time-zone: None
Geo: None
Text: RT @Chelsea_FL: It's Antonio Conte vs Jose Mourinho once again... https://t.co/eT0eNZMoV6
Favourites Count: 18922
Friends Count: 1279
Followers Count: 871
Statuses Count: 9389
hashtags: None
URL: [{'url': 'https://t.co/eT0eNZMoV6', 'expanded_url': 'https://www.football.london/chelsea-fc/fixtures-results/chelsea-conte-mourinho-manchester-united-14562719', 'display_url': 'football.london/chelsea-fc/fix‚Ä¶', 'indices': [66, 89]}]
//////////////////
Name: ChelseaNigeria
Screen-name: saheedAMBO
Tweet created: 2018-04-22 23:38:00
Retweeted: False
Favourited: False
Location: b'Stamford, England/Nigeria'
Time-zone: None
Geo: None
Text: RT @RajiDraj: Chelsea FC in 2018 FA Cup final same as last season. Still fighting for top four till last day.

It is not totally a write o‚Ä¶
Favourites Count: 1407
Friends Count: 5000
Followers Count: 3208
Statuses Count: 38837
hashtags: None
URL: []
//////////////////
Name: m√°rcio leal
Screen-name: marciohexa
Tweet created: 2018-04-22 23:23:19
Retweeted: False
Favourited: False
Location: b'Brazil'
Time-zone: Brasilia
Geo: None
Text: RT @Chelsea_FL: Conte on why he picked Giroud over Morata. https://t.co/0KS3lOopoH
Favourites Count: 11726
Friends Count: 194
Followers Count: 98
Statuses Count: 10766
hashtags: None
URL: [{'url': 'https://t.co/0KS3lOopoH', 'expanded_url': 'https://www.football.london/chelsea-fc/fixtures-results/conte-giroud-morata-chelsea-manchester-14562735', 'display_url': 'football.london/chelsea-fc/fix‚Ä¶', 'indices': [59, 82]}]
//////////////////
Name: Richard M
Screen-name: Richardmou90
Tweet created: 2018-04-22 23:22:37
Retweeted: False
Favourited: False
Location: b''
Time-zone: None
Geo: None
Text: @ImohUmoren Jose loaned  (NOT SOLD) Sallah in Feb, 2015 to go develop his career cos he had better players then. Th‚Ä¶ https://t.co/jk8TnV6Zfj
Favourites Count: 315
Friends Count: 76
Followers Count: 53
Statuses Count: 838
hashtags: None
URL: [{'url': 'https://t.co/jk8TnV6Zfj', 'expanded_url': 'https://twitter.com/i/web/status/988196403922038785', 'display_url': 'twitter.com/i/web/status/9‚Ä¶', 'indices': [117, 140]}]
//////////////////
Name: DJ Brian Hudson
Screen-name: djbrianhudson
Tweet created: 2018-04-22 23:21:02
Retweeted: False
Favourited: False
Location: b'North West, England'
Time-zone: London
Geo: None
Text: üéµ"WEMBLEY, WEMBLEY, WE'RE THE FAMOUS CHELSEA FC AND WE'RE GOING TO WEMBLEY" üéµAGAIN!! #CFC #cfcfamily
Favourites Count: 1580
Friends Count: 3389
Followers Count: 1115
Statuses Count: 4257
hashtags: CFC
URL: []
//////////////////
Name: jas
Screen-name: dclmore
Tweet created: 2018-04-22 23:19:58
Retweeted: False
Favourited: False
Location: b'amigcss'
Time-zone: None
Geo: None
Text: RT @GOAL_ID: FT! Chelsea 2-0 Southampton! | LIVE: https://t.co/pkUrQAq2YK #MatchdayGoal

Final FA Cup akan mempertemukan Chelsea melawan Ma‚Ä¶
Favourites Count: 0
Friends Count: 234
Followers Count: 223
Statuses Count: 366
hashtags: MatchdayGoal
URL: [{'url': 'https://t.co/pkUrQAq2YK', 'expanded_url': 'http://bit.ly/2HkXbnw', 'display_url': 'bit.ly/2HkXbnw', 'indices': [50, 73]}]
//////////////////
Name: Srijan Butola
Screen-name: srijanbutola
Tweet created: 2018-04-22 23:19:46
Retweeted: False
Favourited: False
Location: b''
Time-zone: Pacific Time (US & Canada)
Geo: None
Text: I think Chelsea FC rigged this. https://t.co/o4Q3U7PSdD
Favourites Count: 4477
Friends Count: 129
Followers Count: 33
Statuses Count: 1380
hashtags: None
URL: [{'url': 'https://t.co/o4Q3U7PSdD', 'expanded_url': 'https://twitter.com/PFA/status/988173155670818816', 'display_url': 'twitter.com/PFA/status/988‚Ä¶', 'indices': [32, 55]}]
//////////////////
Name: Chelsea FC News
Screen-name: Chelsea_FL
Tweet created: 2018-04-22 23:09:26
Retweeted: False
Favourited: False
Location: b'London, England'
Time-zone: London
Geo: None
Text: Conte on why he picked Giroud over Morata. https://t.co/0KS3lOopoH
Favourites Count: 1041
Friends Count: 832
Followers Count: 112713
Statuses Count: 73281
hashtags: None
URL: [{'url': 'https://t.co/0KS3lOopoH', 'expanded_url': 'https://www.football.london/chelsea-fc/fixtures-results/conte-giroud-morata-chelsea-manchester-14562735', 'display_url': 'football.london/chelsea-fc/fix‚Ä¶', 'indices': [43, 66]}]
//////////////////
Name: igo alfajar
Screen-name: pwgigo
Tweet created: 2018-04-22 23:01:10
Retweeted: False
Favourited: False
Location: b''
Time-zone: Jakarta
Geo: None
Text: RT @GOAL_ID: FT! Chelsea 2-0 Southampton! | LIVE: https://t.co/pkUrQAq2YK #MatchdayGoal

Final FA Cup akan mempertemukan Chelsea melawan Ma‚Ä¶
Favourites Count: 115
Friends Count: 341
Followers Count: 733
Statuses Count: 23638
hashtags: MatchdayGoal
URL: [{'url': 'https://t.co/pkUrQAq2YK', 'expanded_url': 'http://bit.ly/2HkXbnw', 'display_url': 'bit.ly/2HkXbnw', 'indices': [50, 73]}]
//////////////////
Name: Kiki Widya Sari
Screen-name: Kiki_widya15
Tweet created: 2018-04-22 23:00:30
Retweeted: False
Favourited: False
Location: b'Wonosari, Gunungkidul'
Time-zone: Bangkok
Geo: None
Text: RT @GOAL_ID: 82' GOOAL! Morata! Chelsea 2-0 Southampton! | LIVE: https://t.co/pkUrQAq2YK #MatchdayGoal

Sepertinya Chelsea bakal lolos mena‚Ä¶
Favourites Count: 269
Friends Count: 137
Followers Count: 376
Statuses Count: 7333
hashtags: MatchdayGoal
URL: [{'url': 'https://t.co/pkUrQAq2YK', 'expanded_url': 'http://bit.ly/2HkXbnw', 'display_url': 'bit.ly/2HkXbnw', 'indices': [65, 88]}]
//////////////////

Name: Chelsea üá¨üáß‚öΩ
Screen-name: chelsea_fc_fr
Tweet created: 2018-04-22 22:59:13
Retweeted: False
Favourited: False
Location: b'Londres'
Time-zone: Paris
Geo: None
Text: ANG - Chelsea https://t.co/XqNBm4qMNh #Chelsea https://t.co/XA1hpV6Mol
Favourites Count: 74
Friends Count: 71
Followers Count: 5776
Statuses Count: 33712
hashtags: Chelsea
URL: [{'url': 'https://t.co/XqNBm4qMNh', 'expanded_url': 'http://www.dailymotion.com/video/x6i8tr0', 'display_url': 'dailymotion.com/video/x6i8tr0', 'indices': [14, 37]}, {'url': 'https://t.co/XA1hpV6Mol', 'expanded_url': 'http://www.footiz.com/chelsea/', 'display_url': 'footiz.com/chelsea/', 'indices': [47, 70]}]
//////////////////
Name: Chelsea üá¨üáß‚öΩ
Screen-name: chelsea_fc_fr
Tweet created: 2018-04-22 22:59:12
Retweeted: False
Favourited: False
Location: b'Londres'
Time-zone: Paris
Geo: None
Text: Chelsea v Southampton r√©sum√© du match, 22/04/2018, FA Cup https://t.co/fnF6Y4Gwyp #Chelsea https://t.co/XA1hpV6Mol
Favourites Count: 74
Friends Count: 71
Followers Count: 5776
Statuses Count: 33712
hashtags: Chelsea
URL: [{'url': 'https://t.co/fnF6Y4Gwyp', 'expanded_url': 'https://www.youtube.com/watch%3Fv%3DMX18mqozGOg', 'display_url': 'youtube.com/watch%3Fv%3DMX‚Ä¶', 'indices': [58, 81]}, {'url': 'https://t.co/XA1hpV6Mol', 'expanded_url': 'http://www.footiz.com/chelsea/', 'display_url': 'footiz.com/chelsea/', 'indices': [91, 114]}]
//////////////////
Name: Chelsea üá¨üáß‚öΩ
Screen-name: chelsea_fc_fr
Tweet created: 2018-04-22 22:59:12
Retweeted: False
Favourited: False
Location: b'Londres'
Time-zone: Paris
Geo: None
Text: Chelsea-Southampton: l'incroyable but de Giroud entre 4 d√©fenseurs https://t.co/YKQLCVl1gs #Chelsea https://t.co/XA1hpV6Mol
Favourites Count: 74
Friends Count: 71
Followers Count: 5776
Statuses Count: 33712
hashtags: Chelsea
URL: [{'url': 'https://t.co/YKQLCVl1gs', 'expanded_url': 'https://www.huffingtonpost.fr/2018/04/22/chelsea-southampton-lincroyable-but-de-giroud-entre-4-defenseurs_a_23417521/', 'display_url': 'huffingtonpost.fr/2018/04/22/che‚Ä¶', 'indices': [67, 90]}, {'url': 'https://t.co/XA1hpV6Mol', 'expanded_url': 'http://www.footiz.com/chelsea/', 'display_url': 'footiz.com/chelsea/', 'indices': [100, 123]}]
//////////////////
Name: üï¥iG..psalm.davids üëàüòé
Screen-name: PSALMdAViDS
Tweet created: 2018-04-22 22:49:07
Retweeted: False
Favourited: False
Location: b'Accra - GHANA'
Time-zone: Africa/Accra
Geo: None
Text: Chelsea FC 2 - 0 Southampton

A quick reminder üòã
Favourites Count: 3076
Friends Count: 780
Followers Count: 2147
Statuses Count: 12850
hashtags: None
URL: []
//////////////////
Name: TFS Southampton
Screen-name: TFS_Southampton
Tweet created: 2018-04-22 22:46:29
Retweeted: False
Favourited: False
Location: b''
Time-zone: London
Geo: None
Text: Chelsea FC v Southampton FC with #aronsharpe FA Cup Semi Final https://t.co/vZxPdgtUWp https://t.co/uHhH3D1UZp
Favourites Count: 0
Friends Count: 0
Followers Count: 81
Statuses Count: 5185
hashtags: aronsharpe
URL: [{'url': 'https://t.co/uHhH3D1UZp', 'expanded_url': 'http://dlvr.it/QQQRm6', 'display_url': 'dlvr.it/QQQRm6', 'indices': [87, 110]}]
//////////////////

Since it is a relational database and we are implementing normalization we will be mapping the information collected from the twittter api to the primary key of the entity table. Here we are using twitter api to get data regarding the entity players so we are using player_api_id from players table in the database as a key to create our table

In [11]:
#213501morata#107417#hazard#94086Willian#170323Courtois#319300kante#52133luiz#fabregas#bak#cahill
player_id = 23783
q ="cahill"
q

'cahill'

In the below query we insert the data related to the player in the database.
Running this query again creates duplicates in the database.

In [ ]:
for tweet in tweepy.Cursor(api.search, q=('"%23cahill'),since='2018-04-22', until='2018-04-23').items(20):
    
        Name = tweet.author.name
        Screen_name = tweet.author.screen_name
        Twee_created = tweet.created_at
        Retweeted = tweet.retweeted
        Favourited = tweet.favorited
        Location = tweet.user.location
        Time_zone = tweet.user.time_zone
        Geo = tweet.geo
        Text = tweet.text
        Text=Text.replace('"','')
        Favourites_Count = tweet.user.favourites_count
        Friends_Count = tweet.user.friends_count
        Followers_Count = tweet.user.followers_count
        Statuses_Count = tweet.user.statuses_count
        try:
                Hashtags = tweet.entities['hashtags'][0]['text']
        except IndexError:
                Hashtags = "None"
        URL = tweet.entities['urls']

        
        format_str = """INSERT INTO TWITTER (Player_id, User_Name, Screen_Name, Tweet_created, Retweeted, Favourited, Location, 
                        Time_Zone, Geo, Text, Favourites_Count, Friends_Count, Followers_Count, Statuses_Count, Hashtags, URL)
                        VALUES("{id}", "{user}","{screen}","{created}","{retweet}","{fav}","{loc}","{zone}","{geo}","{text}",
                                "{fav_count}","{friends}","{follow_count}","{status_count}","{hashtags}","{url}");"""
    
        sql_command = format_str.format(id=player_id, user=Name, screen=Screen_name, created=Twee_created, retweet=Retweeted, 
                                       fav=Favourited, loc=Location, zone=Time_zone, geo=Geo, text=Text, fav_count=Favourites_Count,
                                       friends=Friends_Count, follow_count=Followers_Count, status_count=Statuses_Count,
                                        hashtags=Hashtags, url=URL)
        cursor.execute(sql_command)
        
        con.commit()

In [12]:
pd.read_sql("select * from twitter;",con)

,Player_id,User_Name,Screen_Name,Tweet_created,Retweeted,Favourited,Location,Time_Zone,Geo,Text,Favourites_Count,Friends_Count,Followers_Count,Retweet_Count,Hashtags,URL
0,213501,Lynx,LynxApk,2018-04-22 23:36:32,False,False,Meme Land,Mexico City,None,RT @kingzorro81: Last weekend we got hit with ...,114,93,492,146,None,[]
1,213501,lbhkr,LBHKRRecords,2018-04-22 22:42:53,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,1163,1432,127,4035,None,[]
2,213501,Emmanuel Olabayo,bayonuels,2018-04-22 22:30:35,False,False,"Lagos state, Nigeria.",None,None,In a season that had bigger money moves by #Lu...,931,701,424,1399,Lukaku,"[{'url': 'https://t.co/KUakEbyvx4', 'expanded_..."
3,213501,Andrea Fabris,andreafabris96,2018-04-22 21:56:45,False,False,Verderio,Rome,None,Olivier #Giroud e Alvaro #Morata portano il Ch...,23730,1523,538,34752,Giroud,"[{'url': 'https://t.co/UCTBsylBjT', 'expanded_..."
4,213501,Harvey Emby,harveyemby10,2018-04-22 21:40:42,False,False,,None,None,"Great atmosphere at Wembley today, fans were g...",88,179,22,164,None,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_..."
5,213501,Harvey Emby,harveyemby10,2018-04-22 21:38:20,False,False,,None,None,Just to say Giroud‚Äôs goal today should be give...,88,179,22,164,None,"[{'url': 'https://t.co/wVVbYkHoUr', 'expanded_..."
6,213501,"Mary ATP, Arsenal üá∏üá≥",mms_soumare,2018-04-22 21:20:01,False,False,Senegal,None,None,13 buts en #PL c‚Äôest 2 de + que #Morata et ‚Äúqu...,602,1331,408,273,PL,"[{'url': 'https://t.co/XpLDpwAsql', 'expanded_..."
7,213501,SHOWY!,CamiloR531,2018-04-22 21:13:03,False,False,Colombia,Bogota,None,"AS√ç VIVE √ÅLVARO MORATA, CONOCE A SU HERMOSA MU...",59,408,142,5861,Manchester,"[{'url': 'https://t.co/n33ucgNsZC', 'expanded_..."
8,213501,Jordi Garcia Serna,jordigarciatv,2018-04-22 20:36:41,False,False,,Pacific Time (US & Canada),None,Giroud y #Morata gu√≠an al #Chelsea a la final ...,100,39344,42847,7362,Morata,"[{'url': 'https://t.co/YASE8rSheJ', 'expanded_..."
9,213501,malik adams,malikadams1298,2018-04-22 20:15:12,False,False,"Toronto, Ontario",None,None,RT @kingzorro81: Last weekend we got hit with ...,719,971,41,1394,None,[]
10,213501,yunghova,hovie1234,2018-04-22 20:10:07,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,36,22,4,156,None,[]
11,213501,kaito,kaito_z12,2018-04-22 20:06:37,False,False,"Makassar, Indonesia",None,None,RT @kingzorro81: Last weekend we got hit with ...,72,557,22,302,None,[]
12,213501,marzok zeze,ZezeMarzok,2018-04-22 19:57:02,False,False,,None,None,RT @kingzorro81: Last weekend we got hit with ...,64,412,7,142,None,[]
13,213501,Taye6Ô∏è‚É£üî•,6thFlameRebel_,2018-04-22 19:54:15,False,False,Louisiana,None,None,RT @kingzorro81: Last weekend we got hit with ...,828,13,696,1241,None,[]
14,213501,Alva Starr,SplendorNatalie,2018-04-22 19:48:07,False,False,ESPA√ëA,Athens,None,RT @Nataxab3: Me acuerdo cuando dec√≠an q Espa√±...,7546,510,651,34547,Morata,[]
15,213501,Raichel,crypto_chechi,2018-04-22 19:39:56,False,False,"San Jose, CA",None,None,RT @kingzorro81: Last weekend we got hit with ...,100,240,211,136,None,[]
16,213501,karwankurd,karwankurd4,2018-04-22 19:33:50,False,False,Iraq,Hawaii,None,RT @kingzorro81: Last weekend we got hit with ...,284,1671,130,1483,None,[]
17,213501,Agentianonimi.com,AgentiAnonimi,2018-04-22 19:24:52,False,False,"Milano, Lombardia",Rome,None,#FACUP: #Giroud e #Morata portano il #Chelsea ...,6938,424,4977,27293,FACUP,"[{'url': 'https://t.co/daJME93pgT', 'expanded_..."
18,213501,Transfermarkt.pl,TMpl_news,2018-04-22 19:20:01,False,False,,None,None,Chelsea rywalem Manchesteru United w finale ht...,0,12,2888,20138,transfermarkt,"[{'url': 'https://t.co/Q1c4oJb2ie', 'expanded_..."
19,213501,Premier League en espa√±ol,PremierIeagueES,2018-04-22 19:10:49,False,False,,Buenos Aires,None,#FACup\n\n#Chelsea 2 - 0 #Southampton\n\n46' #...,286,33,3195,833,FACup,[]
20,107417,Ariel Montecinos Y.,arielmontecinos,2018-04-22 23:03:11,False,False,"Santiago, Chile",Santiago,None,"@Goal_en_espanol @ChelseaFC_Sp, cuando vi los ...",570,201,161,5471,Chelsea,"[{'url': 'https://t.co/GQLsTAirdA', 'expanded_..."
21,107417,Eshk13,Eshk_chelsea,2018-04-22 22:06:22,False,False,kurdistan,Pacific Time (US & Canada),None,@hazardeden10 ‚ù§üëèüëä \n.\n.\n#chelsea #cfc #hazar...,1108,221,27,27,chelsea,[]
22,107417,And Smith Must Score,AndSmithMustSc1,2018-04-22 22:05:35,False,False,next: tbc,Casablanca,None,RT @AndSmithMustSc1: Although Citeh have strol...,347,984,493,3104,Salah,[]
23,107417,MC,mchino141731,2018-04-22 21:48:36,False,False,,None,None,@zazzatweet @pisto_gol @FabRavezzani Su #Dybal...,1,38,3,99,Dybala,"[{'url': 'https://t.co/dKwRtqbIsq', 'expanded_..."
24,107417,Dave Heasman,daveheez,2018-04-22 21:43:13,False,False,London,London,None,RT @jakeheasman: He can frustrate the life out...,1621,313,277,11409,None,[]
25,107417,Harvey Emby,harveyemby10,2018-04-22 21:40:42,False,False,,None,None,"Great atmosphere at Wembley today, fans were g...",88,179,22,164,None,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_..."
26,107417,AJ,ajaybhatus,2018-04-22 20:54:25,False,False,,None,None,RT @LalitAmbardar: @PiyushGoyalOffc Gaping hol...,3018,600,309,8092,Hazard,[]
27,107417,Thomas Hoskins ‚≠ê,RealTomHoskins,2018-04-22 20:49:02,False,False,"Weston-super-Mare, England",London,None,RT @jakeheasman: He can frustrate the life out...,43037,868,1120,130858,None,[]
28,107417,Jake Heasman,jakeheasman,2018-04-22 20:42:08,False,False,"London, England",London,None,"He can frustrate the life out of me, but games...",3843,1056,1060,11057,None,"[{'url': 'https://t.co/snmiVp16Dc', 'expanded_..."
29,107417,chelseanews24,chelseanews24h,2018-04-22 20:14:16,False,False,London,London,None,"#Hazard, satisfied for the game and results, c...",8,259,466,10587,Hazard,"[{'url': 'https://t.co/q7wNVvbdIM', 'expanded_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,30613,Fredrik Nylund,fredomdet,2018-04-22 14:12:15,False,False,,None,None,Can #F√†bregas find that cutting edge pass agai...,17890,262,201,10543,F√†bregas,[]
140,30613,The Kitman ‚öΩÔ∏èüëï,TheKitmanUK,2018-04-22 07:30:21,False,False,"Bristol, England",London,None,Checkout this Arsenal Home Shirt 2008-10 Fabre...,11548,5001,2697,30138,Arsenal,"[{'url': 'https://t.co/X5MCBAbJyN', 'expanded_..."
141,478393,BLANCHARD,loblanchard13,2018-04-22 22:25:31,False,False,Vaucluse,None,None,RT @JeanLombardozzi: La Une de @laprovence des...,803,260,739,3076,OM,[]
142,478393,Quentin Gil,GILQuentin1,2018-04-22 21:53:32,False,False,France,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,10,453,146,2099,OM,[]
143,478393,OMarseglia,OMarseglia13,2018-04-22 21:29:30,False,False,"Marseille, France",Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,3558,616,126,2642,OM,[]
144,478393,Michael,Michom15,2018-04-22 20:22:44,False,False,,Brussels,None,RT @JeanLombardozzi: La Une de @laprovence des...,1434,365,38,1312,OM,[]
145,478393,Alexomile,alexomile,2018-04-22 20:18:08,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,4,126,572,41464,OM,[]
146,478393,Adrien,Marseillais3_1,2018-04-22 19:54:06,False,False,"Nord, Nord-Pas-de-Calais",Pacific Time (US & Canada),None,RT @JeanLombardozzi: La Une de @laprovence des...,54,181,12,75,OM,[]
147,478393,olympienne13,vanessahidalg13,2018-04-22 19:53:57,False,False,"Tourlaville, France",None,None,RT @JeanLombardozzi: La Une de @laprovence des...,2897,956,68,2782,OM,[]
148,478393,Pastaga,PastagaDST,2018-04-22 19:52:28,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,9986,489,860,33234,OM,[]
149,478393,Alexandre Jacquin,AJac13,2018-04-22 19:51:18,False,False,Marseille,Paris,None,RT @JeanLombardozzi: La Une de @laprovence des...,6060,834,13261,9727,OM,[]
150,478393,DIASSS,Diasss_13,2018-04-22 19:42:33,False,False,Virage Sud,None,None,RT @JeanLombardozzi: La Une de @laprovence des...,20807,363,693,17766,OM,[]
151,478393,#TeamOM,JrmyAh,2018-04-22 19:41:44,False,False,"Marseille, France",London,None,RT @JeanLombardozzi: La Une de @laprovence des...,26980,341,734,52872,OM,[]
152,478393,Pattyn,PattynPatrick13,2018-04-22 19:37:43,False,False,"Marseille, France",None,None,RT @JeanLombardozzi: La Une de @laprovence des...,6346,756,428,4869,OM,[]
153,478393,J√©r√©my Tordjman,Jay_Tordjman,2018-04-22 19:36:09,False,False,"Marseille, et ailleurs...",Pacific Time (US & Canada),None,RT @JeanLombardozzi: La Une de @laprovence des...,338,721,4648,7606,OM,[]
154,478393,Jean Lombardozzi,JeanLombardozzi,2018-04-22 19:34:46,False,False,Marseille,None,None,La Une de @laprovence des Sports ce lundi 23 a...,86,78,775,1509,OM,"[{'url': 'https://t.co/VpZ1degXKM', 'expanded_..."
155,478393,WAHOME,wahome__,2018-04-22 18:52:58,False,False,Kenya,None,None,Bakayoko has improved !!!üëèüëè\nNext year he'll b...,2391,1174,1531,823,Bakayoko,[]
156,478393,Ricky nelly,Rickkynelly,2018-04-22 18:50:23,False,False,Abuja Nigeria,None,None,Seems like #Willian was not angry for being su...,7668,592,141,990,Willian,"[{'url': 'https://t.co/OM4Esj6zWD', 'expanded_..."
157,478393,Tzar,Tzarrahlapane,2018-04-22 17:19:32,False,False,Tshwane,None,None,@ChelseaFC Sell #Bakayoko and sign #Nzonzi,642,412,85,1243,Bakayoko,[]
158,478393,Excelsior! ‚öΩ üéæ,PhilPlanter,2018-04-22 15:44:33,False,False,Galt's Gulch,Quito,None,#Bakayoko makes the simple things seem excruci...,743,2952,1074,8896,Bakayoko,[]
159,478393,Sohaib Khan,KhanGaming_,2018-04-22 15:29:42,False,False,,Casablanca,None,What does #Bakayoko bring??,2712,63,231,1907,Bakayoko,[]
160,478393,Mark Johnson,majohnsonesq,2018-04-22 15:27:24,False,False,Here,America/New_York,None,RT @PhilPlanter: #Conte substitutes #Willian f...,173,85,22,360,Conte,[]
161,23783,Laurenz Vescoli,Laus1507,2018-04-22 21:55:26,False,False,"Innsbruck, Austria",Belgrade,None,Strong against Austin in the air and no mistak...,3571,481,1470,4682,cfc,[]
162,23783,AW,agmow2012,2018-04-22 09:35:09,False,False,"London, England",Amsterdam,None,@OTD_PL @therealstevenpi @ManUtd @Everton @les...,740,329,28,2106,efc,[]
163,23783,Kimberly,candypie22,2018-04-22 01:24:30,False,False,Asgard,None,None,RT @GyspsyLoveserie: @candypie22 @LethalWeapon...,139981,3663,2512,195823,None,[]
164,23783,Kimberly,candypie22,2018-04-22 01:24:13,False,False,Asgard,None,None,RT @GyspsyLoveserie: @Mizcrea @candypie22 @Let...,139981,3663,2512,195823,None,[]
165,23783,Laurenz Vescoli,Laus1507,2018-04-22 21:55:26,False,False,"Innsbruck, Austria",Belgrade,None,Strong against Austin in the air and no mistak...,3571,481,1470,4682,cfc,[]
166,23783,AW,agmow2012,2018-04-22 09:35:09,False,False,"London, England",Amsterdam,None,@OTD_PL @therealstevenpi @ManUtd @Everton @les...,740,329,28,2106,efc,[]
167,23783,Kimberly,candypie22,2018-04-22 01:24:30,False,False,Asgard,None,None,RT @GyspsyLoveserie: @candypie22 @LethalWeapon...,139981,3663,2512,195823,None,[]
168,23783,Kimberly,candypie22,2018-04-22 01:24:13,False,False,Asgard,None,None,RT @GyspsyLoveserie: @Mizcrea @candypie22 @Let...,139981,3663,2512,195823,None,[]

### Question 1.	What are people	saying about me (somebody)?

To check what people are saying about somebody we check 2 columns of our table which are 'hashtags' and 'text'

In [13]:
pd.read_sql("select hashtags, text from twitter where user_name='Lynx';",con)

  Hashtags                                               Text
0     None  RT @kingzorro81: Last weekend we got hit with ...

### Question 2: How viral are my posts?

For checking how viral someones posts are we just take the retweet_count for that user.

In [14]:
pd.read_sql("select retweet_count from twitter where user_name='Lynx';",con)

   Retweet_Count
0            146

### Question 3. How much influence to my posts have?

For checking how much influence my posts have we take the sum of favourites_count, friends_count, followers_count and retweet_count.

In [15]:
pd.read_sql("select favourites_count+friends_count+followers_count+retweet_count AS Influence from twitter where user_name='Lynx';",con)

   Influence
0        845

In [16]:
pd.read_sql("select text from twitter where user_name='Lynx';",con)

                                                Text
0  RT @kingzorro81: Last weekend we got hit with ...

### Question 4: What posts are like mine?

We have a field named 'text' in our database. So we just use 'like' command to check which posts are like me and then display that text.

In [17]:
pd.read_sql("select text from twitter where text like '%weekend%';",con)

                                                Text
0  RT @kingzorro81: Last weekend we got hit with ...
1  RT @kingzorro81: Last weekend we got hit with ...
2  RT @kingzorro81: Last weekend we got hit with ...
3  RT @kingzorro81: Last weekend we got hit with ...
4  RT @kingzorro81: Last weekend we got hit with ...
5  RT @kingzorro81: Last weekend we got hit with ...
6  RT @kingzorro81: Last weekend we got hit with ...
7  RT @kingzorro81: Last weekend we got hit with ...
8  RT @kingzorro81: Last weekend we got hit with ...

### Question 5: What users posts like me?

We have a field named 'text' in our database. So we just use 'like' command to check which posts are like me and then display that users name.

In [18]:
pd.read_sql("select user_name from twitter where text like '%weekend%';",con)

     User_Name
0         Lynx
1        lbhkr
2  malik adams
3     yunghova
4        kaito
5  marzok zeze
6     Taye6Ô∏è‚É£üî•
7      Raichel
8   karwankurd

### Question 6: Who should i be following?

We have a field named followers_count in our database.
So we should be following someone with a high follower_count

In [19]:
pd.read_sql("select user_name,followers_count from twitter order by followers_count DESC;",con)

                                             User_Name  Followers_Count
0                                   Universal Deportes            56101
1                                   Jordi Garcia Serna            42847
2                                          footy90.com            28262
3                                          footy90.com            28262
4                                  Itaipava Fonte Nova            21498
5                                        Simon Johnson            15724
6                                    Alexandre Jacquin            13261
7                                    Vaishali Bhardwaj            11342
8                                  SuperFrankieLampard             8332
9                                              BetYetu             7475
10                                             PRINCE‚ôå             5539
11                                         Jennifer üá≤üáΩ             5134
12                                   Agentianonimi.com             4977
13                                     J√©r√©my Tordjman             4648
14                                     eyefootball.com             4450
15                           Premier League en espa√±ol             3195
16                                         Respondi433             3134
17                                    Transfermarkt.pl             2888
18                                      The Kitman ‚öΩÔ∏èüëï             2697
19                                   Cartoonists' Club             2663
20                                            Kimberly             2512
21                                            Kimberly             2512
22                                            Kimberly             2512
23                                            Kimberly             2512
24                                          Rapha√´l üá®üá¶             2209
25                                                MAKV             2078
26                                            evilways             2043
27                                 HITC Premier League             1999
28                                   Frankline Matanji             1684
29                                    pinkster 2Ô∏è‚É£6Ô∏è‚É£üëë             1671
..                                                 ...              ...
139                                     SoccerCards.ca               54
140                                     SoccerCards.ca               54
141                                      Magic Futebol               53
142                                        malik adams               41
143  kazik boruch kurp gm kadzid≈Ço . drugi tel78144...               40
144                                            Michael               38
145                                      Footy Zone HD               35
146                                              GGZII               31
147                                              GGZII               31
148                                   Chelsea Footybot               28
149                                                 AW               28
150                                                 AW               28
151                                             Eshk13               27
152                                        Harvey Emby               22
153                                        Harvey Emby               22
154                                              kaito               22
155                                        Harvey Emby               22
156                                       Mark Johnson               22
157                                        Paris SGold               22
158                                       Mark Johnson               22
159                                             Betint               21
160                                       Hugo Felacio               21
161                                             Adrien               12
162                                        Dennis Rono               10
163                                        marzok zeze                7
164                                   JUX JUNIOR VIPOR                6
165                                         jaseee6738                6
166                                           yunghova                4
167                                           Debut.gr                4
168                                                 MC                3

[169 rows x 2 columns]

### Question 7: What topics are trending in my domain?

We have 2 columns in our database named 'tweet_created' and 'retweet_count'. So for trending tweets we can check the tweet_created column and retweet_count gives us the most popular tweets.

In [20]:
pd.read_sql("select player_id, user_name, retweet_count from twitter where tweet_created > '2018-04-22 22:42:53' and retweet_count>5000;",con)

  Player_id            User_Name  Retweet_Count
0    107417  Ariel Montecinos Y.           5471
1    319300      #Sohailio Jo Ka           6268
2    319300      #Sohailio Jo Ka           6268

### Question 8: What keywords/hashtags should i add to my post?

We order the retweet_count in descending order. Then check the hashtags used in the top retweets. These give us the keywords/hashtags we should add to the post.

In [21]:
pd.read_sql("select retweet_count, hashtags from twitter order by retweet_count desc;",con)

     Retweet_Count           Hashtags
0           245839              ngolo
1           245837             player
2           195823               None
3           195823               None
4           195823               None
5           195823               None
6           135043  newcastleunitedfc
7           132080           Courtois
8           130858               None
9           113558              Oblak
10          103835             CHESOT
11          101024           Courtois
12           93679              Kant√©
13           92412            Chelsea
14           84322              Kant√©
15           75915               MOTM
16           73886              Oblak
17           65484          davidluiz
18           52872                 OM
19           51300           Courtois
20           51259            Chelsea
21           45797               None
22           42990              Kant√©
23           41464                 OM
24           39702           Courtois
25           34752             Giroud
26           34547             Morata
27           33676           Courtois
28           33529           Courtois
29           33234                 OM
..             ...                ...
139            671               None
140            660             MCISWA
141            501               Luiz
142            493               None
143            411               None
144            381          davidluiz
145            360              Conte
146            360              Conte
147            351                Ooh
148            302               None
149            286           Courtois
150            284               None
151            273                 PL
152            224             Giroud
153            164               None
154            164               None
155            164               None
156            156               None
157            146               None
158            142               None
159            136               None
160             99             Dybala
161             75                 OM
162             42               Luiz
163             27            chelsea
164             23            Willian
165              9             HAZARD
166              4            arsenal
167              4            arsenal
168              4            arsenal

[169 rows x 2 columns]

### Question 9: Should i follow somebody back?

We take the sum of followers_count, retweet_count and friends_count.
So we should follow somebody back if he has high count.

In [22]:
pd.read_sql("select user_name, followers_count + retweet_count + friends_count from twitter order by retweet_count DESC;",con)

                 User_Name  followers_count + retweet_count + friends_count
0              footy90.com                                           291819
1              footy90.com                                           291817
2                 Kimberly                                           201998
3                 Kimberly                                           201998
4                 Kimberly                                           201998
5                 Kimberly                                           201998
6      HITC Premier League                                           137072
7       Augustine Thomford                                           132934
8         Thomas Hoskins ‚≠ê                                           132846
9       Universal Deportes                                           169987
10          TEMITAYO AKEEM                                           106374
11             Jennifer üá≤üáΩ                                           109294
12              Rapha√´l üá®üá¶                                            96196
13        Chelsea Footybot                                            92452
14                  Shelby                                            85376
15            ŸàŸÑŸäÿØ ÿßŸÑÿπÿ™Ÿäÿ®Ÿä                                            79486
16               soporte54                                            77213
17                evilways                                            67654
18                 #TeamOM                                            53947
19           ‚Ñ¢Say_Chelsea‚Ñ¢                                            53994
20         eyefootball.com                                            55806
21                 E.... üíß                                            47090
22   #  G  O  N  E B.¬ÆÔ∏èü¶Å‚ö°Ô∏è                                            45645
23               Alexomile                                            42162
24       Dylan O' Sullivan                                            41265
25           Andrea Fabris                                            36813
26              Alva Starr                                            35708
27              Baxbbota 9                                            34730
28      guadalupe mendozza                                            36977
29                 Pastaga                                            34583
..                     ...                                              ...
139            Don Antonio                                             2613
140          Uzair_Ebay_UK                                             2582
141               Debut.gr                                              549
142      Angkrish Chhabria                                             1044
143        Regina Phalange                                              624
144           Hugo Felacio                                              682
145           Mark Johnson                                              467
146           Mark Johnson                                              467
147          Sra¬∞Afrontaüëèüòö                                              839
148                  kaito                                              881
149             jaseee6738                                              336
150         BetYetu Uganda                                              558
151   Mary ATP, Arsenal üá∏üá≥                                             2012
152                   Nick                                             1069
153            Harvey Emby                                              365
154            Harvey Emby                                              365
155            Harvey Emby                                              365
156               yunghova                                              182
157                   Lynx                                              731
158            marzok zeze                                              561
159                Raichel                                              587
160                     MC                                              140
161                 Adrien                                              268
162                   Idou                                             1960
163                 Eshk13                                              275
164            Dennis Rono                                              226
165       JUX JUNIOR VIPOR                                               95
166        Arsenal forever                                              386
167        Arsenal forever                                              386
168        Arsenal forever                                              386

[169 rows x 2 columns]

### Question 10: What is the best time to post?

We have a column named Tweet_created. So we check what are the top retweet counts and check the time when they were tweeted. Seeing the results below we can say that best time to post is around 17:00:00 to 19:00:00

In [23]:
pd.read_sql("select user_name, tweet_created, retweet_count from twitter order by retweet_count desc;",con)

                 User_Name        Tweet_created  Retweet_Count
0              footy90.com  2018-04-22 17:11:02         245839
1              footy90.com  2018-04-22 16:01:06         245837
2                 Kimberly  2018-04-22 01:24:30         195823
3                 Kimberly  2018-04-22 01:24:13         195823
4                 Kimberly  2018-04-22 01:24:30         195823
5                 Kimberly  2018-04-22 01:24:13         195823
6      HITC Premier League  2018-04-22 18:30:07         135043
7       Augustine Thomford  2018-04-22 14:56:46         132080
8         Thomas Hoskins ‚≠ê  2018-04-22 20:49:02         130858
9       Universal Deportes  2018-04-22 20:34:39         113558
10          TEMITAYO AKEEM  2018-04-22 14:18:56         103835
11             Jennifer üá≤üáΩ  2018-04-22 13:45:12         101024
12              Rapha√´l üá®üá¶  2018-04-22 01:01:18          93679
13        Chelsea Footybot  2018-04-22 19:50:55          92412
14                  Shelby  2018-04-22 01:07:28          84322
15            ŸàŸÑŸäÿØ ÿßŸÑÿπÿ™Ÿäÿ®Ÿä  2018-04-22 19:56:14          75915
16               soporte54  2018-04-22 22:29:00          73886
17                evilways  2018-04-22 17:36:51          65484
18                 #TeamOM  2018-04-22 19:41:44          52872
19           ‚Ñ¢Say_Chelsea‚Ñ¢  2018-04-22 14:59:10          51300
20         eyefootball.com  2018-04-22 19:50:53          51259
21                 E.... üíß  2018-04-22 18:14:04          45797
22   #  G  O  N  E B.¬ÆÔ∏èü¶Å‚ö°Ô∏è  2018-04-22 01:15:39          42990
23               Alexomile  2018-04-22 20:18:08          41464
24       Dylan O' Sullivan  2018-04-22 13:51:17          39702
25           Andrea Fabris  2018-04-22 21:56:45          34752
26              Alva Starr  2018-04-22 19:48:07          34547
27              Baxbbota 9  2018-04-22 20:02:16          33676
28      guadalupe mendozza  2018-04-22 14:51:49          33529
29                 Pastaga  2018-04-22 19:52:28          33234
..                     ...                  ...            ...
139            Don Antonio  2018-04-22 19:06:37            671
140          Uzair_Ebay_UK  2018-04-22 18:01:01            660
141               Debut.gr  2018-04-22 09:00:04            501
142      Angkrish Chhabria  2018-04-22 14:48:50            493
143        Regina Phalange  2018-04-22 16:29:38            411
144           Hugo Felacio  2018-04-22 21:53:05            381
145           Mark Johnson  2018-04-22 15:27:24            360
146           Mark Johnson  2018-04-22 15:27:24            360
147          Sra¬∞Afrontaüëèüòö  2018-04-22 05:52:07            351
148                  kaito  2018-04-22 20:06:37            302
149             jaseee6738  2018-04-22 14:50:51            286
150         BetYetu Uganda  2018-04-22 16:00:23            284
151   Mary ATP, Arsenal üá∏üá≥  2018-04-22 21:20:01            273
152                   Nick  2018-04-22 09:13:53            224
153            Harvey Emby  2018-04-22 21:40:42            164
154            Harvey Emby  2018-04-22 21:38:20            164
155            Harvey Emby  2018-04-22 21:40:42            164
156               yunghova  2018-04-22 20:10:07            156
157                   Lynx  2018-04-22 23:36:32            146
158            marzok zeze  2018-04-22 19:57:02            142
159                Raichel  2018-04-22 19:39:56            136
160                     MC  2018-04-22 21:48:36             99
161                 Adrien  2018-04-22 19:54:06             75
162                   Idou  2018-04-22 08:00:45             42
163                 Eshk13  2018-04-22 22:06:22             27
164            Dennis Rono  2018-04-22 16:19:21             23
165       JUX JUNIOR VIPOR  2018-04-22 19:49:19              9
166        Arsenal forever  2018-04-22 21:11:41              4
167        Arsenal forever  2018-04-22 21:10:59              4
168        Arsenal forever  2018-04-22 21:00:00              4

[169 rows x 3 columns]

### Question 11: Should i add url to my post?

We have the URL column in our table. So we check wheter having a URL affects the retweet count for an user. And seeing the below result we can say that its beneficial to have URL in most cases.

In [24]:
pd.read_sql("select user_name, url,retweet_count from twitter order by retweet_count DESC;",con)

,User_Name,URL,Retweet_Count
0,footy90.com,"[{'url': 'https://t.co/NyLsHUUnhI', 'expanded_...",245839
1,footy90.com,"[{'url': 'https://t.co/uv5eabE2ot', 'expanded_...",245837
2,Kimberly,[],195823
3,Kimberly,[],195823
4,Kimberly,[],195823
5,Kimberly,[],195823
6,HITC Premier League,[],135043
7,Augustine Thomford,[],132080
8,Thomas Hoskins ‚≠ê,[],130858
9,Universal Deportes,"[{'url': 'https://t.co/eSaWQBbfLu', 'expanded_...",113558
10,TEMITAYO AKEEM,[],103835
11,Jennifer üá≤üáΩ,[],101024
12,Rapha√´l üá®üá¶,[],93679
13,Chelsea Footybot,"[{'url': 'https://t.co/VZz19ELYTb', 'expanded_...",92412
14,Shelby,[],84322
15,ŸàŸÑŸäÿØ ÿßŸÑÿπÿ™Ÿäÿ®Ÿä,[],75915
16,soporte54,"[{'url': 'https://t.co/eSaWQBbfLu', 'expanded_...",73886
17,evilways,[],65484
18,#TeamOM,[],52872
19,‚Ñ¢Say_Chelsea‚Ñ¢,[],51300
20,eyefootball.com,"[{'url': 'https://t.co/MqunyPJwv0', 'expanded_...",51259
21,E.... üíß,[],45797
22,# G O N E B.¬ÆÔ∏èü¶Å‚ö°Ô∏è,[],42990
23,Alexomile,[],41464
24,Dylan O' Sullivan,[],39702
25,Andrea Fabris,"[{'url': 'https://t.co/UCTBsylBjT', 'expanded_...",34752
26,Alva Starr,[],34547
27,Baxbbota 9,[],33676
28,guadalupe mendozza,[],33529
29,Pastaga,[],33234
...,...,...,...
139,Don Antonio,[],671
140,Uzair_Ebay_UK,"[{'url': 'https://t.co/1lnykGzjBv', 'expanded_...",660
141,Debut.gr,"[{'url': 'https://t.co/XzpyxonrK0', 'expanded_...",501
142,Angkrish Chhabria,"[{'url': 'https://t.co/424jYFnrvQ', 'expanded_...",493
143,Regina Phalange,"[{'url': 'https://t.co/uOtwoDkGSP', 'expanded_...",411
144,Hugo Felacio,[],381
145,Mark Johnson,[],360
146,Mark Johnson,[],360
147,Sra¬∞Afrontaüëèüòö,[],351
148,kaito,[],302
149,jaseee6738,[],286
150,BetYetu Uganda,"[{'url': 'https://t.co/eDjj8yfZuT', 'expanded_...",284
151,"Mary ATP, Arsenal üá∏üá≥","[{'url': 'https://t.co/XpLDpwAsql', 'expanded_...",273
152,Nick,[],224
153,Harvey Emby,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_...",164
154,Harvey Emby,"[{'url': 'https://t.co/wVVbYkHoUr', 'expanded_...",164
155,Harvey Emby,"[{'url': 'https://t.co/pgZ0vNm7Dq', 'expanded_...",164
156,yunghova,[],156
157,Lynx,[],146
158,marzok zeze,[],142
159,Raichel,[],136
160,MC,"[{'url': 'https://t.co/dKwRtqbIsq', 'expanded_...",99
161,Adrien,[],75
162,Idou,[],42
163,Eshk13,[],27
164,Dennis Rono,[],23
165,JUX JUNIOR VIPOR,[],9
166,Arsenal forever,"[{'url': 'https://t.co/w0p4oUhCdx', 'expanded_...",4
167,Arsenal forever,"[{'url': 'https://t.co/17cDYQwaeG', 'expanded_...",4
168,Arsenal forever,"[{'url': 'https://t.co/MQStLMWuvg', 'expanded_...",4

### Question 12: Whats's my reach?

We can check the reach for an user by checking the 'location' column from our table.

In [25]:
pd.read_sql("select location from twitter where user_name='Lynx';",con)

    Location
0  Meme Land

## LICENSE

MIT License  

Copyright (c) 2018 Prathamesh Tari and Akshay Shinde

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.